In [41]:
import scipy as sp
import numpy as np
import pandas as pd
import pickle

pd.set_option('display.max_rows', None)

In [38]:
def mean_confidence_interval(x, confidence=0.95):
    m, se = np.mean(x), sp.stats.sem(x)
    h = se * sp.stats.t.ppf((1 + confidence) / 2., x.shape[0] - 1)
    return np.round(m - h, 2), np.round(m, 2), np.round(m + h, 2)

def preprocess_string(x):
    if x[0] != "-":
        for i, c in enumerate(x):
            if c.isalpha():
                break
    
        x = x[:i] + " " + x[i:]

        if x[0] == "0" and x[1] != ".":
            i = 1
        else:
            for i in range(1, len(x)):
                if (x[i - 1] == "1"):
                    break
        
        return x[:i] + " " + x[i:]
    else:
        return x

In [3]:
with open("./table_results/diff_results_time_uni.pkl", "rb") as f:
    results = pickle.load(f)

mask_condition = results["mask_condition"]
mask_control = results["mask_control"]
mask_both = results["mask_both"]

In [5]:
keys = [x for x in results.keys() if "mask" not in x]
processed_results = {key: {e: [] for e in ["value", "time"]} for key in keys}

for key in keys:
    tmp_mean = np.mean(results[key]["value"][mask_condition], axis=0)
    processed_results[key]["value"] = mean_confidence_interval(tmp_mean)
    
    processed_results[key]["time"] = mean_confidence_interval(np.array(results[key]["time"]))

In [75]:
df = pd.DataFrame(processed_results).transpose()
df.reset_index(inplace=True)
df["index"] = df["index"].apply(preprocess_string)

df["sigma_min"] = df["index"].apply(lambda x: x.split()[0])
df["sigma"] = df["index"].apply(lambda x: x.split()[1])
df["score_type"] = df["index"].apply(lambda x: x.split()[2])

df["value"] = df.value.apply(lambda x: np.round(np.array(x), 2))
df["time"] = df.time.apply(lambda x: np.round(np.array(x), 2))

df.drop("index", inplace=True, axis=1)
df = df[["sigma_min", "sigma", "score_type", "value", "time"]]
df.sort_values(["sigma_min", "sigma", "score_type"], ascending=False, inplace=True)
df

   sigma_min sigma score_type                  value                   time
3        0.1     1        rnl  [23.96, 24.99, 26.02]  [13.78, 14.53, 15.28]
2        0.1     1         rl  [19.53, 20.45, 21.37]  [14.55, 15.35, 16.16]
1        0.1     1     direct  [22.64, 23.96, 25.28]  [34.33, 35.09, 35.85]
18       0.1  0.75        rnl  [25.46, 26.62, 27.79]  [14.61, 15.35, 16.08]
17       0.1  0.75         rl  [21.15, 21.96, 22.77]   [15.04, 15.97, 16.9]
16       0.1  0.75     direct  [23.32, 25.17, 27.02]  [37.69, 39.04, 40.38]
33       0.1   0.5        rnl  [28.86, 30.02, 31.18]  [15.46, 16.96, 18.47]
32       0.1   0.5         rl  [21.45, 21.91, 22.37]   [17.29, 18.09, 18.9]
31       0.1   0.5     direct  [25.88, 27.96, 30.04]   [40.9, 42.16, 43.42]
48       0.1  0.25        rnl  [31.22, 33.28, 35.35]  [16.58, 17.62, 18.66]
47       0.1  0.25         rl   [21.87, 22.9, 23.92]  [19.09, 19.96, 20.83]
46       0.1  0.25     direct  [25.71, 29.03, 32.34]  [42.84, 44.08, 45.31]
63       0.1     0        rnl  [35.75, 38.76, 41.77]  [15.95, 16.95, 17.95]
62       0.1     0         rl   [22.27, 23.6, 24.94]   [20.14, 21.22, 22.3]
61       0.1     0     direct  [29.24, 31.78, 34.33]  [45.91, 46.48, 47.05]
6       0.01     1        rnl  [25.39, 26.41, 27.43]   [13.8, 14.49, 15.18]
5       0.01     1         rl  [18.73, 19.45, 20.16]  [13.87, 14.66, 15.46]
4       0.01     1     direct  [22.03, 23.46, 24.89]   [36.18, 37.14, 38.1]
21      0.01  0.75        rnl  [26.12, 27.85, 29.58]  [15.12, 16.03, 16.94]
20      0.01  0.75         rl  [19.75, 20.68, 21.61]   [16.9, 18.42, 19.95]
19      0.01  0.75     direct   [21.18, 22.89, 24.6]  [39.68, 41.19, 42.69]
36      0.01   0.5        rnl   [30.53, 31.52, 32.5]  [16.37, 17.31, 18.25]
35      0.01   0.5         rl  [21.51, 22.14, 22.77]   [19.87, 20.69, 21.5]
34      0.01   0.5     direct   [25.15, 27.3, 29.44]  [43.06, 43.75, 44.44]
51      0.01  0.25        rnl  [35.57, 39.11, 42.65]   [15.8, 16.75, 17.71]
50      0.01  0.25         rl   [22.9, 24.24, 25.59]  [19.43, 20.23, 21.03]
49      0.01  0.25     direct  [26.77, 30.41, 34.06]  [45.85, 46.72, 47.58]
66      0.01     0        rnl  [52.68, 59.62, 66.57]  [14.67, 15.93, 17.18]
65      0.01     0         rl  [24.81, 26.08, 27.36]    [20.6, 21.65, 22.7]
64      0.01     0     direct  [28.93, 35.58, 42.23]  [46.57, 47.49, 48.41]
9      0.001     1        rnl  [24.74, 25.79, 26.84]  [13.42, 14.18, 14.95]
8      0.001     1         rl  [17.87, 18.74, 19.61]  [14.04, 14.95, 15.86]
7      0.001     1     direct  [20.61, 22.08, 23.54]  [36.55, 37.52, 38.49]
24     0.001  0.75        rnl   [27.14, 28.12, 29.1]  [16.06, 16.86, 17.66]
23     0.001  0.75         rl   [18.9, 19.71, 20.52]  [16.95, 18.41, 19.87]
22     0.001  0.75     direct  [22.42, 23.16, 23.91]  [40.61, 41.63, 42.65]
39     0.001   0.5        rnl  [29.05, 31.39, 33.73]  [15.81, 17.85, 19.89]
38     0.001   0.5         rl  [20.43, 21.55, 22.66]  [19.04, 20.55, 22.06]
37     0.001   0.5     direct  [22.87, 24.47, 26.07]  [42.52, 43.73, 44.94]
54     0.001  0.25        rnl  [35.45, 37.52, 39.59]  [17.03, 17.97, 18.92]
53     0.001  0.25         rl   [22.4, 23.21, 24.01]   [19.56, 20.3, 21.04]
52     0.001  0.25     direct   [24.9, 27.12, 29.33]  [44.96, 45.98, 46.99]
69     0.001     0        rnl  [67.28, 74.16, 81.03]  [13.49, 14.75, 16.01]
68     0.001     0         rl   [23.6, 24.87, 26.14]  [20.46, 21.45, 22.43]
67     0.001     0     direct  [27.69, 31.58, 35.47]  [45.98, 47.21, 48.44]
12    0.0001     1        rnl  [24.67, 25.49, 26.32]   [13.37, 14.73, 16.1]
11    0.0001     1         rl  [17.08, 18.08, 19.09]   [14.87, 16.34, 17.8]
10    0.0001     1     direct   [20.1, 21.04, 21.98]  [35.12, 36.99, 38.87]
27    0.0001  0.75        rnl  [24.25, 26.18, 28.11]  [16.29, 17.21, 18.14]
26    0.0001  0.75         rl  [18.43, 19.24, 20.06]  [17.21, 18.74, 20.27]
25    0.0001  0.75     direct   [20.17, 21.4, 22.64]  [40.35, 41.34, 42.32]
42    0.0001   0.5        rnl  [25.73, 29.25, 32.78]  [18.18, 19.96, 21.73]
41    0.0001   0.5         rl   [19.44, 21.27, 23.1]  [18.34, 20.39, 22.45]
40    0.0001   0.5     direct  [19.52, 22.07, 24.62]   [42.85, 45.63, 48.4]
57    0.0001  0.25        rnl  [30.81, 34.22, 37.62]  [16.69, 17.66, 18.63]
56    0.0001  0.25         rl   [21.16, 22.28, 23.4]  [20.09, 21.15, 22.21]
55    0.0001  0.25     direct  [22.01, 24.28, 26.55]  [44.05, 45.24, 46.43]
72    0.0001     0        rnl  [79.99, 88.15, 96.31]   [13.13, 14.0, 14.86]
71    0.0001     0         rl  [23.73, 24.61, 25.49]  [20.67, 21.78, 22.89]
70    0.0001     0     direct   [27.75, 29.8, 31.85]  [46.85, 48.06, 49.28]
15         0     1        rnl  [23.58, 26.45, 29.31]  [13.74, 15.23, 16.72]
14         0     1         rl  [17.43, 18.54, 19.64]  [15.67, 17.14, 18.61]
13         0     1     direct  [19.74, 22.54, 25.35]  [36.51, 37.64, 38.77]
30         0  0.75        rnl   [24.4, 27.07, 29.74]  [15.95, 16.48, 17.01]
29         0  0.75         rl  [18.31, 19.66, 21.02]  [17.94, 18.76, 19.57]
28         0  0.75     direct  [18.75, 21.11, 23.46]   [40.29, 41.65, 43.0]
45         0   0.5        rnl  [27.29, 29.75, 32.21]   [17.18, 17.94, 18.7]
44         0   0.5         rl   [20.2, 21.32, 22.44]  [20.07, 21.58, 23.09]
43         0   0.5     direct   [21.0, 23.13, 25.26]   [39.8, 47.06, 54.32]
60         0  0.25        rnl  [30.49, 33.62, 36.74]  [16.79, 18.41, 20.04]
59         0  0.25         rl   [21.2, 22.55, 23.91]  [19.69, 21.18, 22.67]
58         0  0.25     direct  [21.05, 22.89, 24.74]  [43.41, 45.01, 46.61]
75         0     0        rnl   [63.23, 71.92, 80.6]  [12.98, 14.51, 16.05]
74         0     0         rl  [23.54, 24.78, 26.02]  [21.63, 23.14, 24.65]
73         0     0     direct  [25.73, 28.75, 31.76]  [46.79, 47.66, 48.54]
0          -     -       true  [20.16, 20.16, 20.16]     [0.01, 0.01, 0.02]

In [78]:
group = df.groupby(["score_type"])[["value", "time"]].mean().reset_index()
group["value"] = group.value.apply(lambda x: np.round(np.array(x), 2))
group["time"] = group.time.apply(lambda x: np.round(np.array(x), 2))
group

  score_type                  value                   time
0     direct  [23.41, 25.72, 28.03]  [41.59, 43.02, 44.45]
1         rl   [20.71, 21.75, 22.8]  [18.12, 19.28, 20.45]
2        rnl  [34.15, 37.09, 40.03]  [15.29, 16.39, 17.48]
3       true  [20.16, 20.16, 20.16]     [0.01, 0.01, 0.02]

In [97]:
group = df[df.score_type.isin(["rl", "direct"])].copy()
group["value"] = group.value.apply(lambda x: x - np.array([20.16, 20.16, 20.16]))
group["value"] = group.value.apply(lambda x: np.round(np.array(x), 2))
group["time"] = group.time.apply(lambda x: np.round(np.array(x), 2))
group

   sigma_min sigma score_type                  value                   time
2        0.1     1         rl    [-0.63, 0.29, 1.21]  [14.55, 15.35, 16.16]
1        0.1     1     direct      [2.48, 3.8, 5.12]  [34.33, 35.09, 35.85]
17       0.1  0.75         rl      [0.99, 1.8, 2.61]   [15.04, 15.97, 16.9]
16       0.1  0.75     direct     [3.16, 5.01, 6.86]  [37.69, 39.04, 40.38]
32       0.1   0.5         rl     [1.29, 1.75, 2.21]   [17.29, 18.09, 18.9]
31       0.1   0.5     direct      [5.72, 7.8, 9.88]   [40.9, 42.16, 43.42]
47       0.1  0.25         rl     [1.71, 2.74, 3.76]  [19.09, 19.96, 20.83]
46       0.1  0.25     direct    [5.55, 8.87, 12.18]  [42.84, 44.08, 45.31]
62       0.1     0         rl     [2.11, 3.44, 4.78]   [20.14, 21.22, 22.3]
61       0.1     0     direct   [9.08, 11.62, 14.17]  [45.91, 46.48, 47.05]
5       0.01     1         rl    [-1.43, -0.71, 0.0]  [13.87, 14.66, 15.46]
4       0.01     1     direct      [1.87, 3.3, 4.73]   [36.18, 37.14, 38.1]
20      0.01  0.75         rl    [-0.41, 0.52, 1.45]   [16.9, 18.42, 19.95]
19      0.01  0.75     direct     [1.02, 2.73, 4.44]  [39.68, 41.19, 42.69]
35      0.01   0.5         rl     [1.35, 1.98, 2.61]   [19.87, 20.69, 21.5]
34      0.01   0.5     direct     [4.99, 7.14, 9.28]  [43.06, 43.75, 44.44]
50      0.01  0.25         rl     [2.74, 4.08, 5.43]  [19.43, 20.23, 21.03]
49      0.01  0.25     direct    [6.61, 10.25, 13.9]  [45.85, 46.72, 47.58]
65      0.01     0         rl      [4.65, 5.92, 7.2]    [20.6, 21.65, 22.7]
64      0.01     0     direct   [8.77, 15.42, 22.07]  [46.57, 47.49, 48.41]
8      0.001     1         rl  [-2.29, -1.42, -0.55]  [14.04, 14.95, 15.86]
7      0.001     1     direct     [0.45, 1.92, 3.38]  [36.55, 37.52, 38.49]
23     0.001  0.75         rl   [-1.26, -0.45, 0.36]  [16.95, 18.41, 19.87]
22     0.001  0.75     direct      [2.26, 3.0, 3.75]  [40.61, 41.63, 42.65]
38     0.001   0.5         rl      [0.27, 1.39, 2.5]  [19.04, 20.55, 22.06]
37     0.001   0.5     direct     [2.71, 4.31, 5.91]  [42.52, 43.73, 44.94]
53     0.001  0.25         rl     [2.24, 3.05, 3.85]   [19.56, 20.3, 21.04]
52     0.001  0.25     direct     [4.74, 6.96, 9.17]  [44.96, 45.98, 46.99]
68     0.001     0         rl     [3.44, 4.71, 5.98]  [20.46, 21.45, 22.43]
67     0.001     0     direct   [7.53, 11.42, 15.31]  [45.98, 47.21, 48.44]
11    0.0001     1         rl  [-3.08, -2.08, -1.07]   [14.87, 16.34, 17.8]
10    0.0001     1     direct    [-0.06, 0.88, 1.82]  [35.12, 36.99, 38.87]
26    0.0001  0.75         rl   [-1.73, -0.92, -0.1]  [17.21, 18.74, 20.27]
25    0.0001  0.75     direct     [0.01, 1.24, 2.48]  [40.35, 41.34, 42.32]
41    0.0001   0.5         rl    [-0.72, 1.11, 2.94]  [18.34, 20.39, 22.45]
40    0.0001   0.5     direct    [-0.64, 1.91, 4.46]   [42.85, 45.63, 48.4]
56    0.0001  0.25         rl      [1.0, 2.12, 3.24]  [20.09, 21.15, 22.21]
55    0.0001  0.25     direct     [1.85, 4.12, 6.39]  [44.05, 45.24, 46.43]
71    0.0001     0         rl     [3.57, 4.45, 5.33]  [20.67, 21.78, 22.89]
70    0.0001     0     direct    [7.59, 9.64, 11.69]  [46.85, 48.06, 49.28]
14         0     1         rl  [-2.73, -1.62, -0.52]  [15.67, 17.14, 18.61]
13         0     1     direct    [-0.42, 2.38, 5.19]  [36.51, 37.64, 38.77]
29         0  0.75         rl    [-1.85, -0.5, 0.86]  [17.94, 18.76, 19.57]
28         0  0.75     direct     [-1.41, 0.95, 3.3]   [40.29, 41.65, 43.0]
44         0   0.5         rl     [0.04, 1.16, 2.28]  [20.07, 21.58, 23.09]
43         0   0.5     direct      [0.84, 2.97, 5.1]   [39.8, 47.06, 54.32]
59         0  0.25         rl     [1.04, 2.39, 3.75]  [19.69, 21.18, 22.67]
58         0  0.25     direct     [0.89, 2.73, 4.58]  [43.41, 45.01, 46.61]
74         0     0         rl     [3.38, 4.62, 5.86]  [21.63, 23.14, 24.65]
73         0     0     direct     [5.57, 8.59, 11.6]  [46.79, 47.66, 48.54]

In [79]:
df[df.score_type == "rl"]

   sigma_min sigma score_type                  value                   time
2        0.1     1         rl  [19.53, 20.45, 21.37]  [14.55, 15.35, 16.16]
17       0.1  0.75         rl  [21.15, 21.96, 22.77]   [15.04, 15.97, 16.9]
32       0.1   0.5         rl  [21.45, 21.91, 22.37]   [17.29, 18.09, 18.9]
47       0.1  0.25         rl   [21.87, 22.9, 23.92]  [19.09, 19.96, 20.83]
62       0.1     0         rl   [22.27, 23.6, 24.94]   [20.14, 21.22, 22.3]
5       0.01     1         rl  [18.73, 19.45, 20.16]  [13.87, 14.66, 15.46]
20      0.01  0.75         rl  [19.75, 20.68, 21.61]   [16.9, 18.42, 19.95]
35      0.01   0.5         rl  [21.51, 22.14, 22.77]   [19.87, 20.69, 21.5]
50      0.01  0.25         rl   [22.9, 24.24, 25.59]  [19.43, 20.23, 21.03]
65      0.01     0         rl  [24.81, 26.08, 27.36]    [20.6, 21.65, 22.7]
8      0.001     1         rl  [17.87, 18.74, 19.61]  [14.04, 14.95, 15.86]
23     0.001  0.75         rl   [18.9, 19.71, 20.52]  [16.95, 18.41, 19.87]
38     0.001   0.5         rl  [20.43, 21.55, 22.66]  [19.04, 20.55, 22.06]
53     0.001  0.25         rl   [22.4, 23.21, 24.01]   [19.56, 20.3, 21.04]
68     0.001     0         rl   [23.6, 24.87, 26.14]  [20.46, 21.45, 22.43]
11    0.0001     1         rl  [17.08, 18.08, 19.09]   [14.87, 16.34, 17.8]
26    0.0001  0.75         rl  [18.43, 19.24, 20.06]  [17.21, 18.74, 20.27]
41    0.0001   0.5         rl   [19.44, 21.27, 23.1]  [18.34, 20.39, 22.45]
56    0.0001  0.25         rl   [21.16, 22.28, 23.4]  [20.09, 21.15, 22.21]
71    0.0001     0         rl  [23.73, 24.61, 25.49]  [20.67, 21.78, 22.89]
14         0     1         rl  [17.43, 18.54, 19.64]  [15.67, 17.14, 18.61]
29         0  0.75         rl  [18.31, 19.66, 21.02]  [17.94, 18.76, 19.57]
44         0   0.5         rl   [20.2, 21.32, 22.44]  [20.07, 21.58, 23.09]
59         0  0.25         rl   [21.2, 22.55, 23.91]  [19.69, 21.18, 22.67]
74         0     0         rl  [23.54, 24.78, 26.02]  [21.63, 23.14, 24.65]

In [100]:
group = df.copy()
group["value"] = group.value.apply(lambda x: x - np.array([20.16, 20.16, 20.16]))
group = group.groupby(["sigma_min", "score_type"])[["value", "time"]].mean().reset_index()
group["value"] = group.value.apply(lambda x: np.round(np.array(x), 2))
group["time"] = group.time.apply(lambda x: np.round(np.array(x), 2))
group.sort_values(["sigma_min", "score_type"], ascending=False, inplace=True)
group

   sigma_min score_type                 value                   time
15       0.1        rnl  [8.89, 10.57, 12.26]  [15.28, 16.28, 17.29]
14       0.1         rl     [1.09, 2.0, 2.91]  [17.22, 18.12, 19.02]
13       0.1     direct     [5.2, 7.42, 9.64]   [40.33, 41.37, 42.4]
12      0.01        rnl  [13.9, 16.74, 19.59]   [15.15, 16.1, 17.05]
11      0.01         rl    [1.38, 2.36, 3.34]  [18.13, 19.13, 20.13]
10      0.01     direct   [4.65, 7.77, 10.88]  [42.27, 43.26, 44.24]
9      0.001        rnl  [16.57, 19.24, 21.9]  [15.16, 16.32, 17.49]
8      0.001         rl    [0.48, 1.46, 2.43]  [18.01, 19.13, 20.25]
7      0.001     direct     [3.54, 5.52, 7.5]   [42.12, 43.21, 44.3]
6     0.0001        rnl  [16.93, 20.5, 24.07]  [15.53, 16.71, 17.89]
5     0.0001         rl   [-0.19, 0.94, 2.07]  [18.24, 19.68, 21.12]
4     0.0001     direct    [1.75, 3.56, 5.37]  [41.84, 43.45, 45.06]
3          0        rnl  [13.64, 17.6, 21.56]   [15.33, 16.51, 17.7]
2          0         rl   [-0.02, 1.21, 2.45]   [19.0, 20.36, 21.72]
1          0     direct    [1.09, 3.52, 5.95]   [41.36, 43.8, 46.25]
0          -       true       [0.0, 0.0, 0.0]     [0.01, 0.01, 0.02]

In [101]:
group = df.copy()
group["value"] = group.value.apply(lambda x: x - np.array([20.16, 20.16, 20.16]))
group = group.groupby(["sigma", "score_type"])[["value", "time"]].mean().reset_index()
group["value"] = group.value.apply(lambda x: np.round(np.array(x), 2))
group["time"] = group.time.apply(lambda x: np.round(np.array(x), 2))
group.sort_values(["sigma", "score_type"], ascending=False, inplace=True)
group

   sigma score_type                  value                   time
15     1        rnl     [4.31, 5.67, 7.02]  [13.62, 14.63, 15.65]
14     1         rl  [-2.03, -1.11, -0.19]   [14.6, 15.69, 16.78]
13     1     direct     [0.86, 2.46, 4.05]  [35.74, 36.88, 38.02]
12  0.75        rnl      [5.31, 7.01, 8.7]  [15.61, 16.39, 17.17]
11  0.75         rl    [-0.85, 0.09, 1.04]  [16.81, 18.06, 19.31]
10  0.75     direct     [1.01, 2.59, 4.17]  [39.72, 40.97, 42.21]
9    0.5        rnl   [8.13, 10.23, 12.32]    [16.6, 18.0, 19.41]
8    0.5         rl     [0.45, 1.48, 2.51]   [18.92, 20.26, 21.6]
7    0.5     direct     [2.72, 4.83, 6.93]   [41.83, 44.47, 47.1]
6   0.25        rnl  [12.55, 15.39, 18.23]  [16.58, 17.68, 18.79]
5   0.25         rl     [1.75, 2.88, 4.01]  [19.57, 20.56, 21.56]
4   0.25     direct     [3.93, 6.59, 9.24]  [44.22, 45.41, 46.58]
3      0        rnl   [39.63, 46.36, 53.1]  [14.04, 15.23, 16.41]
2      0         rl     [3.43, 4.63, 5.83]   [20.7, 21.85, 22.99]
1      0     direct   [7.71, 11.34, 14.97]  [46.42, 47.38, 48.34]
0      -       true        [0.0, 0.0, 0.0]     [0.01, 0.01, 0.02]

In [104]:
df["diff_mean"] = df.value.apply(lambda x: x[1] - 20.16)
df["diff_mean_abs"] = df.diff_mean.apply(abs)
df.sort_values("diff_mean_abs")

,sigma_min,sigma,score_type,value,time,diff_mean,diff_mean_abs
0,-,-,true,"[20.16, 20.16, 20.16]","[0.01, 0.01, 0.02]",0.00,0.00
2,0.1,1,rl,"[19.53, 20.45, 21.37]","[14.55, 15.35, 16.16]",0.29,0.29
23,0.001,0.75,rl,"[18.9, 19.71, 20.52]","[16.95, 18.41, 19.87]",-0.45,0.45
29,0,0.75,rl,"[18.31, 19.66, 21.02]","[17.94, 18.76, 19.57]",-0.50,0.50
20,0.01,0.75,rl,"[19.75, 20.68, 21.61]","[16.9, 18.42, 19.95]",0.52,0.52
5,0.01,1,rl,"[18.73, 19.45, 20.16]","[13.87, 14.66, 15.46]",-0.71,0.71
10,0.0001,1,direct,"[20.1, 21.04, 21.98]","[35.12, 36.99, 38.87]",0.88,0.88
26,0.0001,0.75,rl,"[18.43, 19.24, 20.06]","[17.21, 18.74, 20.27]",-0.92,0.92
28,0,0.75,direct,"[18.75, 21.11, 23.46]","[40.29, 41.65, 43.0]",0.95,0.95
41,0.0001,0.5,rl,"[19.44, 21.27, 23.1]","[18.34, 20.39, 22.45]",1.11,1.11
44,0,0.5,rl,"[20.2, 21.32, 22.44]","[20.07, 21.58, 23.09]",1.16,1.16
25,0.0001,0.75,direct,"[20.17, 21.4, 22.64]","[40.35, 41.34, 42.32]",1.24,1.24
38,0.001,0.5,rl,"[20.43, 21.55, 22.66]","[19.04, 20.55, 22.06]",1.39,1.39
8,0.001,1,rl,"[17.87, 18.74, 19.61]","[14.04, 14.95, 15.86]",-1.42,1.42
14,0,1,rl,"[17.43, 18.54, 19.64]","[15.67, 17.14, 18.61]",-1.62,1.62
32,0.1,0.5,rl,"[21.45, 21.91, 22.37]","[17.29, 18.09, 18.9]",1.75,1.75
17,0.1,0.75,rl,"[21.15, 21.96, 22.77]","[15.04, 15.97, 16.9]",1.80,1.80
40,0.0001,0.5,direct,"[19.52, 22.07, 24.62]","[42.85, 45.63, 48.4]",1.91,1.91
7,0.001,1,direct,"[20.61, 22.08, 23.54]","[36.55, 37.52, 38.49]",1.92,1.92
35,0.01,0.5,rl,"[21.51, 22.14, 22.77]","[19.87, 20.69, 21.5]",1.98,1.98
11,0.0001,1,rl,"[17.08, 18.08, 19.09]","[14.87, 16.34, 17.8]",-2.08,2.08
56,0.0001,0.25,rl,"[21.16, 22.28, 23.4]","[20.09, 21.15, 22.21]",2.12,2.12
13,0,1,direct,"[19.74, 22.54, 25.35]","[36.51, 37.64, 38.77]",2.38,2.38
59,0,0.25,rl,"[21.2, 22.55, 23.91]","[19.69, 21.18, 22.67]",2.39,2.39
58,0,0.25,direct,"[21.05, 22.89, 24.74]","[43.41, 45.01, 46.61]",2.73,2.73
19,0.01,0.75,direct,"[21.18, 22.89, 24.6]","[39.68, 41.19, 42.69]",2.73,2.73
47,0.1,0.25,rl,"[21.87, 22.9, 23.92]","[19.09, 19.96, 20.83]",2.74,2.74
43,0,0.5,direct,"[21.0, 23.13, 25.26]","[39.8, 47.06, 54.32]",2.97,2.97
22,0.001,0.75,direct,"[22.42, 23.16, 23.91]","[40.61, 41.63, 42.65]",3.00,3.00
53,0.001,0.25,rl,"[22.4, 23.21, 24.01]","[19.56, 20.3, 21.04]",3.05,3.05
4,0.01,1,direct,"[22.03, 23.46, 24.89]","[36.18, 37.14, 38.1]",3.30,3.30
62,0.1,0,rl,"[22.27, 23.6, 24.94]","[20.14, 21.22, 22.3]",3.44,3.44
1,0.1,1,direct,"[22.64, 23.96, 25.28]","[34.33, 35.09, 35.85]",3.80,3.80
50,0.01,0.25,rl,"[22.9, 24.24, 25.59]","[19.43, 20.23, 21.03]",4.08,4.08
55,0.0001,0.25,direct,"[22.01, 24.28, 26.55]","[44.05, 45.24, 46.43]",4.12,4.12
37,0.001,0.5,direct,"[22.87, 24.47, 26.07]","[42.52, 43.73, 44.94]",4.31,4.31
71,0.0001,0,rl,"[23.73, 24.61, 25.49]","[20.67, 21.78, 22.89]",4.45,4.45
74,0,0,rl,"[23.54, 24.78, 26.02]","[21.63, 23.14, 24.65]",4.62,4.62
68,0.001,0,rl,"[23.6, 24.87, 26.14]","[20.46, 21.45, 22.43]",4.71,4.71
3,0.1,1,rnl,"[23.96, 24.99, 26.02]","[13.78, 14.53, 15.28]",4.83,4.83
16,0.1,0.75,direct,"[23.32, 25.17, 27.02]","[37.69, 39.04, 40.38]",5.01,5.01
12,0.0001,1,rnl,"[24.67, 25.49, 26.32]","[13.37, 14.73, 16.1]",5.33,5.33
9,0.001,1,rnl,"[24.74, 25.79, 26.84]","[13.42, 14.18, 14.95]",5.63,5.63
65,0.01,0,rl,"[24.81, 26.08, 27.36]","[20.6, 21.65, 22.7]",5.92,5.92
27,0.0001,0.75,rnl,"[24.25, 26.18, 28.11]","[16.29, 17.21, 18.14]",6.02,6.02
6,0.01,1,rnl,"[25.39, 26.41, 27.43]","[13.8, 14.49, 15.18]",6.25,6.25
15,0,1,rnl,"[23.58, 26.45, 29.31]","[13.74, 15.23, 16.72]",6.29,6.29
18,0.1,0.75,rnl,"[25.46, 26.62, 27.79]","[14.61, 15.35, 16.08]",6.46,6.46
30,0,0.75,rnl,"[24.4, 27.07, 29.74]","[15.95, 16.48, 17.01]",6.91,6.91
52,0.001,0.25,direct,"[24.9, 27.12, 29.33]","[44.96, 45.98, 46.99]",6.96,6.96
34,0.01,0.5,direct,"[25.15, 27.3, 29.44]","[43.06, 43.75, 44.44]",7.14,7.14
21,0.01,0.75,rnl,"[26.12, 27.85, 29.58]","[15.12, 16.03, 16.94]",7.69,7.69
31,0.1,0.5,direct,"[25.88, 27.96, 30.04]","[40.9, 42.16, 43.42]",7.80,7.80
24,0.001,0.75,rnl,"[27.14, 28.12, 29.1]","[16.06, 16.86, 17.66]",7.96,7.96
73,0,0,direct,"[25.73, 28.75, 31.76]","[46.79, 47.66, 48.54]",8.59,8.59
46,0.1,0.25,direct,"[25.71, 29.03, 32.34]","[42.84, 44.08, 45.31]",8.87,8.87
42,0.0001,0.5,rnl,"[25.73, 29.25, 32.78]","[18.18, 19.96, 21.73]",9.09,9.09
45,0,0.5,rnl,"[27.29, 29.75, 32.21]","[17.18, 17.94, 18.7]",9.59,9.59
70,0.0001,0,direct,"[27.75, 29.8, 31.85]","[46.85, 48.06, 49.28]",9.64,9.64
33,0.1,0.5,rnl,"[28.86, 30.02, 31.18]","[15.46, 16.96, 18.47]",9.86,9.86
49,0.01,0.25,direct,"[26.77, 30.41, 34.06]","[45.85, 46.72, 47.58]",10.25,10.25
39,0.001,0.5,rnl,"[29.05, 31.39, 33.73]","[15.81, 17.85, 19.89]",11.23,11.23
36,0.01,0.5,rnl,"[30.53, 31.52, 32.5]","[16.37, 17.31, 18.25]",11.36,11.36
67,0.001,0,direct,"[27.69, 31.58, 35.47]","[45.98, 47.21, 48.44]",11.42,11.42
61,0.1,0,direct,"[29.24, 31.78, 34.33]","[45.91, 46.48, 47.05]",11.62,11.62
48,0.1,0.25,rnl,"[31.22, 33.28, 35.35]","[16.58, 17.62, 18.66]",13.12,13.12
60,0,0.25,rnl,"[30.49, 33.62, 36.74]","[16.79, 18.41, 20.04]",13.46,13.46
57,0.0001,0.25,rnl,"[30.81, 34.22, 37.62]","[16.69, 17.66, 18.63]",14.06,14.06
64,0.01,0,direct,"[28.93, 35.58, 42.23]","[46.57, 47.49, 48.41]",15.42,15.42
54,0.001,0.25,rnl,"[35.45, 37.52, 39.59]","[17.03, 17.97, 18.92]",17.36,17.36
63,0.1,0,rnl,"[35.75, 38.76, 41.77]","[15.95, 16.95, 17.95]",18.60,18.60
51,0.01,0.25,rnl,"[35.57, 39.11, 42.65]","[15.8, 16.75, 17.71]",18.95,18.95
66,0.01,0,rnl,"[52.68, 59.62, 66.57]","[14.67, 15.93, 17.18]",39.46,39.46
75,0,0,rnl,"[63.23, 71.92, 80.6]","[12.98, 14.51, 16.05]",51.76,51.76
69,0.001,0,rnl,"[67.28, 74.16, 81.03]","[13.49, 14.75, 16.01]",54.00,54.00
72,0.0001,0,rnl,"[79.99, 88.15, 96.31]","[13.13, 14.0, 14.86]",67.99,67.99