In [56]:
from pathlib import Path 
import sys
import os 
import numpy as np
import scipy as sp
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import seaborn as sns
import matplotlib.pyplot as plt

## Path to result

In [5]:
dims = np.array([20, 40, 80, 160, 320])

gt = 0.5 * np.log(1/(0.36**(dims/2)))
true_mi = dict(zip(dims, gt))

In [6]:
results_tsm = {"dimensions": [], 
              "lr": [], 
              "sb_var": [], 
              "mse": []}

results_ctsm = {"dimensions": [], 
              "lr": [], 
              "sb_var": [], 
              "mse": []}

### Results TSM

In [7]:
result_dir_tsm = Path("../../project_folder/results/mi_experiments/dre-cfm/dre-cfm_tsm_sweeps/")

In [8]:
for run in os.listdir(result_dir_tsm):
    run_split = run.split("_")
    dimension, lr, sb_var = int(run_split[4]), float(run_split[6]), float(run_split[-1])
    if sb_var==0:
        continue
    results_tsm["dimensions"].append(dimension)
    results_tsm["lr"].append(lr)
    results_tsm["sb_var"].append(sb_var)

    ratio = np.load(result_dir_tsm / run / "metrics" / "estim_logr.npy")
    
    ratio_mean = ratio.mean()
    results_tsm["mse"].append(np.abs(ratio_mean - true_mi[dimension]))

In [9]:
results_tsm_df = pd.DataFrame(results_tsm)

In [10]:
results_tsm_df.groupby(["dimensions", "lr", "sb_var"]).mean()

                                mse
dimensions lr     sb_var
20         0.0005 0.1      0.573805
                  0.5      0.156566
                  1.0      0.358851
           0.0010 0.1      0.899803
                  0.5      0.126670
                  1.0      0.441034
           0.0050 0.1      1.771329
                  0.5      0.202602
                  1.0      0.290744
40         0.0005 0.1      0.817895
                  0.5      0.577952
                  1.0      1.573715
           0.0010 0.1      1.706341
                  0.5      0.617361
                  1.0      1.021182
           0.0050 0.1      2.459503
                  0.5      1.735265
                  1.0      7.470318
80         0.0005 0.1      1.051867
                  0.5      2.296177
                  1.0      5.151409
           0.0010 0.1      2.434530
                  0.5      2.255263
                  1.0      1.957072
           0.0050 0.1      0.716196
                  0.5      4.940764
                  1.0      6.546100
160        0.0005 0.1      0.041910
                  0.5      6.723759
                  1.0      9.125541
           0.0010 0.1      1.222653
                  0.5      6.967565
                  1.0      6.958841
           0.0050 0.1      8.884697
                  0.5     13.158549
                  1.0     13.907916
320        0.0005 0.1      5.307517
                  0.5     16.823799
                  1.0     22.441401
           0.0010 0.1      6.675358
                  0.5     18.523058
                  1.0     22.221662
           0.0050 0.1     33.993366
                  0.5     37.330430
                  1.0     43.564600

Best configurations to retrain TSM: 

Dimension 20: 
* lr 1e-3
* sb_var 0.5

Dimension 40:
* lr 5e-4
* sb_var 0.5

Dimension 80:
* lr 5e-3
* sb_var 0.1

Dimension 160:
* lr 5e-4
* sb_var 0.1

Dimension 320: 
* lr 5e-4
* sb_var 0.1

### Results CTSM

In [11]:
result_dir_ctsm = Path("../../project_folder/results/mi_experiments/dre-cfm/dre-cfm_sb_sweeps")

In [12]:
for run in os.listdir(result_dir_ctsm):
    run_split = run.split("_")
    dimension, lr, sb_var = int(run_split[4]), float(run_split[6]), float(run_split[-1])
    results_ctsm["dimensions"].append(dimension)
    results_ctsm["lr"].append(lr)
    results_ctsm["sb_var"].append(sb_var)

    ratio = np.load(result_dir_ctsm / run / "metrics" / "estim_logr.npy")
    
    ratio_mean = ratio.mean()
    results_ctsm["mse"].append(np.abs(ratio_mean - true_mi[dimension]))

In [13]:
results_ctsm_df = pd.DataFrame(results_ctsm)

In [14]:
results_ctsm_df.groupby(["dimensions", "lr", "sb_var"]).mean()

                                mse
dimensions lr     sb_var
20         0.0005 0.1      0.581319
                  0.5      0.227317
                  1.0      0.216081
           0.0010 0.1      1.007366
                  0.5      0.271100
                  1.0      0.229909
           0.0050 0.1      1.500231
                  0.5      0.270725
                  1.0      0.174948
40         0.0005 0.1      1.210912
                  0.5      0.348210
                  1.0      0.459331
           0.0010 0.1      1.460035
                  0.5      0.367991
                  1.0      0.472429
           0.0050 0.1      1.713695
                  0.5      0.307719
                  1.0      0.214768
80         0.0005 0.1      2.459885
                  0.5      0.254904
                  1.0      0.708108
           0.0010 0.1      2.175420
                  0.5      0.284431
                  1.0      0.621560
           0.0050 0.1      1.134994
                  0.5      1.661460
                  1.0      0.837532
160        0.0005 0.1      3.070606
                  0.5      0.018746
                  1.0      1.175519
           0.0010 0.1      0.333248
                  0.5      0.671132
                  1.0      1.137069
           0.0050 0.1     11.613992
                  0.5      6.527090
                  1.0      5.890540
320        0.0005 0.1      1.927281
                  0.5      0.458792
                  1.0      1.427605
           0.0010 0.1      7.530234
                  0.5      2.898284
                  1.0      2.064826
           0.0050 0.1     39.599845
                  0.5     25.864948
                  1.0     21.487527

Best configurations to retrain TSM: 

Dimension 20: 
* lr 5e-3
* sb_var 1

Dimension 40:
* lr 5e-3
* sb_var 1

Dimension 80:
* lr 5e-4
* sb_var 0.5

Dimension 160:
* lr 5e-4
* sb_var 0.5

Dimension 320:
* lr 5e-4
* sb_var 0.5

## Plot performance vs stochasticity

In [ ]:
sns.set_theme(style="whitegrid", context="talk")

plt.figure(figsize=(6,4))

ax = sns.boxplot(
    data=results_ctsm_df,
    x="dimensions",
    y="mse",
    hue="sb_var",
    width=0.6,
    fliersize=3,
    linewidth=1.2
)

ax.set_xlabel("Dimensions")
ax.set_ylabel("MSE")

# Legend in top-left
ax.legend(
    title="SB Variance",
    loc="upper left",
    fontsize=12,        # legend text size
    title_fontsize=13  # legend title size
)

sns.despine()
plt.tight_layout()
plt.title("CTSM", fontsize=15)
plt.savefig("../../project_folder/plots/mse_boxplot_ctsm.pdf", format="pdf", bbox_inches="tight")
plt.show()