In [1]:
import numpy as np
from pathlib import Path 
import matplotlib.pyplot as plt
import os
import pandas as pd

## Get metrics for the normal scRatio

In [3]:
dims = np.array([20, 40, 80, 160, 320])
gt = 0.5 * np.log(1/(0.36**(dims/2)))
true_mi = dict(zip(dims, gt))

In [4]:
result_dir = Path("../../project_folder/results/mi_experiments/scRatio/simulate_under_uncond/")
results = {"Config": [], 
           "MSE": [],
           "Dimensions": [], 
           "Run": []
          }

for file in os.listdir(result_dir):
    for dim in [20, 40, 80, 160, 320]:
        ratios = np.load(result_dir / file / f"ratios_{dim}.npy")
        ratios_split = np.split(ratios, 3)
        split_avgs = [arr.mean() for arr in ratios_split]
        # MSE with real values 
        split_avgs_mse = [np.abs(avg - true_mi[dim]) for avg in split_avgs]
        for i, avg in enumerate(split_avgs_mse):
            results["Config"].append(file)
            results["MSE"].append(avg)
            results["Dimensions"].append(dim)
            results["Run"].append(i)

In [5]:
results_df = pd.DataFrame(results)
results_df.groupby(["Config", "Dimensions"]).mean()

                                  MSE  Run
Config          Dimensions
deterministic   20           0.225716  1.0
                40           0.350860  1.0
                80           0.577399  1.0
                160          0.900653  1.0
                320         22.746783  1.0
sigmamin_0.01   20           0.189550  1.0
                40           0.301945  1.0
                80           0.460380  1.0
                160          0.928741  1.0
                320         22.468209  1.0
sigmamin_0.1    20           0.168616  1.0
                40           0.275584  1.0
                80           0.491375  1.0
                160          0.881354  1.0
                320         22.929056  1.0
stochastic_0.1  20           0.193387  1.0
                40           0.277977  1.0
                80           0.424398  1.0
                160          1.019987  1.0
                320         17.864439  1.0
stochastic_0.25 20           0.155849  1.0
                40           0.288463  1.0
                80           0.492947  1.0
                160          1.027249  1.0
                320          0.455203  1.0
stochastic_0.5  20           0.171360  1.0
                40           0.684693  1.0
                80           0.615038  1.0
                160          0.878889  1.0
                320          2.645389  1.0

In [6]:
results_df.groupby(["Config", "Dimensions"]).std() / np.sqrt(3)

                                 MSE      Run
Config          Dimensions
deterministic   20          0.010957  0.57735
                40          0.019071  0.57735
                80          0.061889  0.57735
                160         0.069879  0.57735
                320         0.175548  0.57735
sigmamin_0.01   20          0.029034  0.57735
                40          0.027128  0.57735
                80          0.054934  0.57735
                160         0.082716  0.57735
                320         0.112678  0.57735
sigmamin_0.1    20          0.020587  0.57735
                40          0.048093  0.57735
                80          0.059583  0.57735
                160         0.045329  0.57735
                320         0.209671  0.57735
stochastic_0.1  20          0.027626  0.57735
                40          0.025672  0.57735
                80          0.061264  0.57735
                160         0.055091  0.57735
                320         0.042756  0.57735
stochastic_0.25 20          0.019601  0.57735
                40          0.045201  0.57735
                80          0.082772  0.57735
                160         0.181180  0.57735
                320         0.145356  0.57735
stochastic_0.5  20          0.014461  0.57735
                40          0.464352  0.57735
                80          0.084035  0.57735
                160         0.076568  0.57735
                320         0.127967  0.57735

## Results baseline DRECFM

Results for the competing models were obtained using the code at https://github.com/ksnxr/dre-prob-paths using the "TwoSB" option. The adapted repo will be made available upon request, message alessandro.palma@helmholtz-munich.de.

In [7]:
path_dre_cfm = Path("../../project_folder/results/mi_experiments/dre-cfm/dre-cfm_sb/")

In [8]:
results_baseline = {"MSE": [],
                    "Dimensions": [], 
                    "Run": []
                      }

In [9]:
for file in os.listdir(path_dre_cfm):
    _, dimensions, run = file.split("_")  
    dimensions = int(dimensions)
    run = int(run)
    results_baseline["Run"].append(run)
    results_baseline["Dimensions"].append(dimensions)
    
    ratios_cfm = np.load(path_dre_cfm / file / "metrics" / "estim_logr.npy")
    ratio_mean = ratios_cfm.mean()
    results_baseline["MSE"].append(np.abs(ratio_mean - true_mi[dimensions]))

In [10]:
results_baseline_df = pd.DataFrame(results_baseline)

In [11]:
results_baseline_df.groupby("Dimensions").mean()

                 MSE  Run
Dimensions
20          0.249783  2.0
40          0.429196  2.0
80          0.657164  2.0
160         0.744094  2.0
320         3.392826  2.0

In [12]:
results_baseline_df.groupby("Dimensions").std() / np.sqrt(3)

                 MSE      Run
Dimensions
20          0.006884  0.57735
40          0.011284  0.57735
80          0.021570  0.57735
160         0.150374  0.57735
320         0.053206  0.57735

## Results baseline TFM

In [13]:
path_dre_tsm = Path("../../project_folder/results/mi_experiments/dre-cfm/dre-cfm_tsm/")

In [14]:
results_baseline_tsm = {"MSE": [],
                        "Dimensions": [], 
                        "Run": []
                       }

In [15]:
for file in os.listdir(path_dre_tsm):
    _, dimensions, run = file.split("_")  
    dimensions = int(dimensions)
    run = int(run)
    results_baseline_tsm["Run"].append(run)
    results_baseline_tsm["Dimensions"].append(dimensions)
    
    ratios_cfm = np.load(path_dre_tsm / file / "metrics" / "estim_logr.npy")
    ratio_mean = ratios_cfm.mean()
    results_baseline_tsm["MSE"].append(np.abs(ratio_mean - true_mi[dimensions]))

In [16]:
results_baseline_tsm_df = pd.DataFrame(results_baseline_tsm)

In [17]:
results_baseline_tsm_df.groupby("Dimensions").mean()

                  MSE  Run
Dimensions
20           0.041602  2.0
40           0.425706  2.0
80           1.290737  2.0
160          5.417780  2.0
320         28.853004  2.0

In [18]:
results_baseline_tsm_df.groupby("Dimensions").std() / np.sqrt(3)

                 MSE      Run
Dimensions
20          0.015343  0.57735
40          0.022983  0.57735
80          0.038564  0.57735
160         0.051311  0.57735
320         1.197651  0.57735