In [1]:
import scipy as sp
import numpy as np
import pandas as pd
from sklearn.metrics import precision_recall_curve, auc
import matplotlib.pyplot as plt
from pathlib import Path  
import scanpy as sc
import os 
from model_evaluation import *

sc.settings.set_figure_params(figsize=(3, 3))

Initialize subsampling rates

In [2]:
subsampling_rates = [0.0, 0.05, 0.10, 0.20, 0.30, 0.40, 0.45, 0.50]
# subsampling_rates = [0.10, 0.30, 0.45]

## Evaluate Mrvi

In [3]:
mrvi_result_path = Path("/home/icb/alessandro.palma/environment/scFM_density_estimation/project_folder/results/abundance_test_experiment/mrvi")
results_mrvi_per_oversamp, results_mrvi_per_run = compute_evaluation_metrics(mrvi_result_path, "mrvi", subsampling_rates, 3)

/ictstr01/home/icb/alessandro.palma/environment/scFM_density_estimation/notebooks/differential_abundance_analysis/model_evaluation.py:132: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  results_per_run["value"].append(sp.stats.pearsonr(results_per_oversamp_df_i[metric],

In [4]:
results_mrvi_per_run

                               metric     value  run
0                   spearman_log_odds  0.851906    0
1                    pearson_log_odds  0.665817    0
2                   spearman_log_odds  0.855938    1
3                    pearson_log_odds  0.703736    1
4                   spearman_log_odds  0.863270    2
5                    pearson_log_odds  0.636894    2
6              corr_p_major_cluster_p  1.000000    0
7                mean_p_major_cluster  0.950000    0
8              corr_p_minor_cluster_p -1.000000    0
9                mean_p_minor_cluster  0.050000    0
10                   corr_auc_score_p  0.841682    0
11                     mean_auc_score  0.887365    0
12  corr_non_abundant_over_abundant_p -0.873664    0
13    mean_non_abundant_over_abundant  0.129733    0
14           corr_correct_sign_prop_p  0.687668    0
15             mean_correct_sign_prop  0.975288    0
16                        corr_ks_D_p  0.816169    0
17                          mean_ks_D  0.816550    0
18                  corr_w_distance_p  0.991128    0
19                    mean_w_distance  1.375703    0
20                         corr_run_p       NaN    0
21                           mean_run  0.000000    0
22             corr_p_major_cluster_p  1.000000    1
23               mean_p_major_cluster  0.950000    1
24             corr_p_minor_cluster_p -1.000000    1
25               mean_p_minor_cluster  0.050000    1
26                   corr_auc_score_p  0.741785    1
27                     mean_auc_score  0.889979    1
28  corr_non_abundant_over_abundant_p -0.757668    1
29    mean_non_abundant_over_abundant  0.142841    1
30           corr_correct_sign_prop_p  0.612035    1
31             mean_correct_sign_prop  0.973452    1
32                        corr_ks_D_p  0.635143    1
33                          mean_ks_D  0.811573    1
34                  corr_w_distance_p  0.986046    1
35                    mean_w_distance  1.399496    1
36                         corr_run_p       NaN    1
37                           mean_run  1.000000    1
38             corr_p_major_cluster_p  1.000000    2
39               mean_p_major_cluster  0.950000    2
40             corr_p_minor_cluster_p -1.000000    2
41               mean_p_minor_cluster  0.050000    2
42                   corr_auc_score_p  0.727400    2
43                     mean_auc_score  0.877834    2
44  corr_non_abundant_over_abundant_p -0.820512    2
45    mean_non_abundant_over_abundant  0.146982    2
46           corr_correct_sign_prop_p  0.618944    2
47             mean_correct_sign_prop  0.974917    2
48                        corr_ks_D_p  0.709887    2
49                          mean_ks_D  0.821684    2
50                  corr_w_distance_p  0.974276    2
51                    mean_w_distance  1.336027    2
52                         corr_run_p       NaN    2
53                           mean_run  2.000000    2

In [5]:
results_mrvi_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1)

,,auc_score,non_abundant_over_abundant,correct_sign_prop,ks_D,w_distance
p_major_cluster,p_minor_cluster,,,,,
0.50,0.50,0.465574,0.422843,0.408618,0.259781,0.082087
0.55,0.45,0.657164,0.291895,0.856563,0.510249,0.162138
0.60,0.40,0.805004,0.211218,0.949816,0.744516,0.262006
0.70,0.30,0.872288,0.182771,0.971775,0.836960,0.519815
0.80,0.20,0.901050,0.153755,0.982648,0.853962,0.833159
0.90,0.10,0.900619,0.159030,0.979171,0.848441,1.193009
0.95,0.05,0.891887,0.132644,0.974529,0.808235,1.453113
1.00,0.00,0.862672,0.127882,0.969957,0.793132,1.465103

In [6]:
results_mrvi_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1).mean(0)

auc_score                     0.794532
non_abundant_over_abundant    0.210255
correct_sign_prop             0.886635
ks_D                          0.706909
w_distance                    0.746304
dtype: float64

In [7]:
results_mrvi_per_run.groupby("metric").mean()

                                      value  run
metric
corr_auc_score_p                   0.770289  1.0
corr_correct_sign_prop_p           0.639549  1.0
corr_ks_D_p                        0.720399  1.0
corr_non_abundant_over_abundant_p -0.817281  1.0
corr_p_major_cluster_p             1.000000  1.0
corr_p_minor_cluster_p            -1.000000  1.0
corr_run_p                              NaN  1.0
corr_w_distance_p                  0.983817  1.0
mean_auc_score                     0.885059  1.0
mean_correct_sign_prop             0.974552  1.0
mean_ks_D                          0.816602  1.0
mean_non_abundant_over_abundant    0.139852  1.0
mean_p_major_cluster               0.950000  1.0
mean_p_minor_cluster               0.050000  1.0
mean_run                           1.000000  1.0
mean_w_distance                    1.370408  1.0
pearson_log_odds                   0.668816  1.0
spearman_log_odds                  0.857038  1.0

In [8]:
results_mrvi_per_run.groupby("metric").std()/np.sqrt(3)

                                      value      run
metric
corr_auc_score_p                   0.035937  0.57735
corr_correct_sign_prop_p           0.024142  0.57735
corr_ks_D_p                        0.052521  0.57735
corr_non_abundant_over_abundant_p  0.033524  0.57735
corr_p_major_cluster_p             0.000000  0.57735
corr_p_minor_cluster_p             0.000000  0.57735
corr_run_p                              NaN  0.57735
corr_w_distance_p                  0.004991  0.57735
mean_auc_score                     0.003691  0.57735
mean_correct_sign_prop             0.000560  0.57735
mean_ks_D                          0.002919  0.57735
mean_non_abundant_over_abundant    0.005199  0.57735
mean_p_major_cluster               0.000000  0.57735
mean_p_minor_cluster               0.000000  0.57735
mean_run                           0.577350  0.57735
mean_w_distance                    0.018512  0.57735
pearson_log_odds                   0.019354  0.57735
spearman_log_odds                  0.003326  0.57735

## Evaluate Milo

In [9]:
milo_result_path = Path("/home/icb/alessandro.palma/environment/scFM_density_estimation/project_folder/results/abundance_test_experiment/milo")
results_milo_per_oversamp, results_milo_per_run = compute_evaluation_metrics(milo_result_path, "milo", subsampling_rates, 3)

/ictstr01/home/icb/alessandro.palma/environment/scFM_density_estimation/notebooks/differential_abundance_analysis/model_evaluation.py:132: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  results_per_run["value"].append(sp.stats.pearsonr(results_per_oversamp_df_i[metric],

In [10]:
results_milo_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1)

,,auc_score,non_abundant_over_abundant,correct_sign_prop,ks_D,w_distance
p_major_cluster,p_minor_cluster,,,,,
0.50,0.50,0.274165,1.066215,0.460497,0.030220,0.013952
0.55,0.45,0.363674,0.769794,0.815033,0.169882,0.068747
0.60,0.40,0.594102,0.472712,0.928692,0.472810,0.262006
0.70,0.30,0.895121,0.250662,0.969600,0.785782,0.775814
0.80,0.20,0.950541,0.164865,0.976699,0.865017,1.422843
0.90,0.10,0.968390,0.103334,0.980389,0.908712,2.491338
0.95,0.05,0.973953,0.077910,0.982131,0.915560,3.437391
1.00,0.00,0.979066,0.048726,0.986533,0.924804,5.593940

In [11]:
results_milo_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1).mean(0)

auc_score                     0.749877
non_abundant_over_abundant    0.369277
correct_sign_prop             0.887447
ks_D                          0.634098
w_distance                    1.758254
dtype: float64

In [12]:
results_milo_per_run.groupby("metric").mean()

                                      value  run
metric
corr_auc_score_p                   0.904504  1.0
corr_correct_sign_prop_p           0.712395  1.0
corr_ks_D_p                        0.911991  1.0
corr_non_abundant_over_abundant_p -0.909223  1.0
corr_p_major_cluster_p             1.000000  1.0
corr_p_minor_cluster_p            -1.000000  1.0
corr_run_p                              NaN  1.0
corr_w_distance_p                  0.923355  1.0
mean_auc_score                     0.973803  1.0
mean_correct_sign_prop             0.983017  1.0
mean_ks_D                          0.916359  1.0
mean_non_abundant_over_abundant    0.076657  1.0
mean_p_major_cluster               0.950000  1.0
mean_p_minor_cluster               0.050000  1.0
mean_run                           1.000000  1.0
mean_w_distance                    3.840890  1.0
pearson_log_odds                   0.827560  1.0
spearman_log_odds                  0.907669  1.0

In [13]:
results_milo_per_run.groupby("metric").std()/np.sqrt(3)

                                      value      run
metric
corr_auc_score_p                   0.000395  0.57735
corr_correct_sign_prop_p           0.000549  0.57735
corr_ks_D_p                        0.000441  0.57735
corr_non_abundant_over_abundant_p  0.000464  0.57735
corr_p_major_cluster_p             0.000000  0.57735
corr_p_minor_cluster_p             0.000000  0.57735
corr_run_p                              NaN  0.57735
corr_w_distance_p                  0.000080  0.57735
mean_auc_score                     0.000014  0.57735
mean_correct_sign_prop             0.000038  0.57735
mean_ks_D                          0.000015  0.57735
mean_non_abundant_over_abundant    0.000043  0.57735
mean_p_major_cluster               0.000000  0.57735
mean_p_minor_cluster               0.000000  0.57735
mean_run                           0.577350  0.57735
mean_w_distance                    0.000352  0.57735
pearson_log_odds                   0.000007  0.57735
spearman_log_odds                  0.000855  0.57735

## Evaluate MELD

In [14]:
meld_result_path = Path("/home/icb/alessandro.palma/environment/scFM_density_estimation/project_folder/results/abundance_test_experiment/meld")
results_meld_per_oversamp, results_meld_per_run = compute_evaluation_metrics(meld_result_path, "meld", subsampling_rates, 3)

/ictstr01/home/icb/alessandro.palma/environment/scFM_density_estimation/notebooks/differential_abundance_analysis/model_evaluation.py:132: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  results_per_run["value"].append(sp.stats.pearsonr(results_per_oversamp_df_i[metric],

In [15]:

results_meld_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1)

,,auc_score,non_abundant_over_abundant,correct_sign_prop,ks_D,w_distance
p_major_cluster,p_minor_cluster,,,,,
0.50,0.50,0.629607,0.279145,0.021553,0.845292,0.006299
0.55,0.45,0.925110,0.144445,0.996399,0.819965,0.047419
0.60,0.40,0.935041,0.144197,0.996346,0.813418,0.100588
0.70,0.30,0.933073,0.163245,0.996081,0.805553,0.201706
0.80,0.20,0.932196,0.159887,0.996240,0.806972,0.314571
0.90,0.10,0.933963,0.156661,0.996240,0.807507,0.424336
0.95,0.05,0.930835,0.155483,0.996452,0.810150,0.489415
1.00,0.00,0.934540,0.152889,0.996240,0.807468,0.554932

In [16]:
results_meld_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1).mean(0)

auc_score                     0.894296
non_abundant_over_abundant    0.169494
correct_sign_prop             0.874444
ks_D                          0.814540
w_distance                    0.267408
dtype: float64

In [17]:
results_meld_per_run.groupby("metric").mean()

                                      value  run
metric
corr_auc_score_p                   0.539850  1.0
corr_correct_sign_prop_p           0.529237  1.0
corr_ks_D_p                       -0.689945  1.0
corr_non_abundant_over_abundant_p -0.461875  1.0
corr_p_major_cluster_p             1.000000  1.0
corr_p_minor_cluster_p            -1.000000  1.0
corr_run_p                              NaN  1.0
corr_w_distance_p                  0.999030  1.0
mean_auc_score                     0.933113  1.0
mean_correct_sign_prop             0.996311  1.0
mean_ks_D                          0.808375  1.0
mean_non_abundant_over_abundant    0.155011  1.0
mean_p_major_cluster               0.950000  1.0
mean_p_minor_cluster               0.050000  1.0
mean_run                           1.000000  1.0
mean_w_distance                    0.489561  1.0
pearson_log_odds                   0.661332  1.0
spearman_log_odds                  0.864003  1.0

In [18]:
results_meld_per_run.groupby("metric").std()/np.sqrt(3)

                                     value      run
metric
corr_auc_score_p                   0.00000  0.57735
corr_correct_sign_prop_p           0.00000  0.57735
corr_ks_D_p                        0.00000  0.57735
corr_non_abundant_over_abundant_p  0.00000  0.57735
corr_p_major_cluster_p             0.00000  0.57735
corr_p_minor_cluster_p             0.00000  0.57735
corr_run_p                             NaN  0.57735
corr_w_distance_p                  0.00000  0.57735
mean_auc_score                     0.00000  0.57735
mean_correct_sign_prop             0.00000  0.57735
mean_ks_D                          0.00000  0.57735
mean_non_abundant_over_abundant    0.00000  0.57735
mean_p_major_cluster               0.00000  0.57735
mean_p_minor_cluster               0.00000  0.57735
mean_run                           0.57735  0.57735
mean_w_distance                    0.00000  0.57735
pearson_log_odds                   0.00000  0.57735
spearman_log_odds                  0.00000  0.57735

## Deterministic

In [19]:
scratio_det_result_path = Path("/home/icb/alessandro.palma/environment/scFM_density_estimation/project_folder/results/abundance_test_experiment/scRatio/original_runs/deterministic")
results_scratio_det_per_oversamp, results_scratio_det_per_run = compute_evaluation_metrics(scratio_det_result_path, "scRatio", subsampling_rates, 3)

/ictstr01/home/icb/alessandro.palma/environment/scFM_density_estimation/notebooks/differential_abundance_analysis/model_evaluation.py:132: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  results_per_run["value"].append(sp.stats.pearsonr(results_per_oversamp_df_i[metric],

In [20]:
results_scratio_det_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1)

,,auc_score,non_abundant_over_abundant,correct_sign_prop,ks_D,w_distance
p_major_cluster,p_minor_cluster,,,,,
0.50,0.50,0.309107,0.933513,0.444821,0.041957,0.005554
0.55,0.45,0.455529,0.647508,0.832098,0.251910,0.047998
0.60,0.40,0.658027,0.430813,0.926040,0.479445,0.167700
0.70,0.30,0.835349,0.320786,0.971404,0.693732,0.422485
0.80,0.20,0.923454,0.226354,0.981589,0.829917,0.894201
0.90,0.10,0.939229,0.188256,0.977988,0.843670,1.419460
0.95,0.05,0.948526,0.162087,0.982878,0.859349,1.996910
1.00,0.00,0.967533,0.057883,0.986285,0.883900,6.790151

In [21]:
results_scratio_det_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1).mean(0)

auc_score                     0.754594
non_abundant_over_abundant    0.370900
correct_sign_prop             0.887888
ks_D                          0.610485
w_distance                    1.468057
dtype: float64

In [22]:
results_scratio_det_per_run.groupby("metric").mean()

                                      value  run
metric
corr_auc_score_p                   0.911100  1.0
corr_correct_sign_prop_p           0.691435  1.0
corr_ks_D_p                        0.917462  1.0
corr_non_abundant_over_abundant_p -0.911907  1.0
corr_p_major_cluster_p             1.000000  1.0
corr_p_minor_cluster_p            -1.000000  1.0
corr_run_p                              NaN  1.0
corr_w_distance_p                  0.759390  1.0
mean_auc_score                     0.951763  1.0
mean_correct_sign_prop             0.982384  1.0
mean_ks_D                          0.862307  1.0
mean_non_abundant_over_abundant    0.136075  1.0
mean_p_major_cluster               0.950000  1.0
mean_p_minor_cluster               0.050000  1.0
mean_run                           1.000000  1.0
mean_w_distance                    3.402174  1.0
pearson_log_odds                   0.928384  1.0
spearman_log_odds                  0.872801  1.0

In [36]:
results_scratio_det_per_run.groupby("metric").std() / np.sqrt(3)

                                      value      run
metric
corr_auc_score_p                   0.012483  0.57735
corr_correct_sign_prop_p           0.022168  0.57735
corr_ks_D_p                        0.012192  0.57735
corr_non_abundant_over_abundant_p  0.027894  0.57735
corr_p_major_cluster_p             0.000000  0.57735
corr_p_minor_cluster_p             0.000000  0.57735
corr_run_p                              NaN  0.57735
corr_w_distance_p                  0.005797  0.57735
mean_auc_score                     0.001591  0.57735
mean_correct_sign_prop             0.000073  0.57735
mean_ks_D                          0.003355  0.57735
mean_non_abundant_over_abundant    0.004823  0.57735
mean_p_major_cluster               0.000000  0.57735
mean_p_minor_cluster               0.000000  0.57735
mean_run                           0.577350  0.57735
mean_w_distance                    0.012408  0.57735
pearson_log_odds                   0.000690  0.57735
spearman_log_odds                  0.012382  0.57735

## Deterministic sigma_min

In [24]:
scratio_det_sigma_min_result_path = Path("/home/icb/alessandro.palma/environment/scFM_density_estimation/project_folder/results/abundance_test_experiment/scRatio/deterministic_sigma_min")
results_scratio_det_sigma_min_per_oversamp, results_scratio_det_sigma_min_per_run = compute_evaluation_metrics(scratio_det_sigma_min_result_path, "scRatio", subsampling_rates, 3)

/ictstr01/home/icb/alessandro.palma/environment/scFM_density_estimation/notebooks/differential_abundance_analysis/model_evaluation.py:132: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  results_per_run["value"].append(sp.stats.pearsonr(results_per_oversamp_df_i[metric],

In [25]:
results_scratio_det_sigma_min_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1)

,,auc_score,non_abundant_over_abundant,correct_sign_prop,ks_D,w_distance
p_major_cluster,p_minor_cluster,,,,,
0.50,0.50,0.320448,0.897921,0.418267,0.044231,0.008980
0.55,0.45,0.491472,0.621683,0.854217,0.263005,0.055710
0.60,0.40,0.741321,0.376618,0.944485,0.578183,0.203275
0.70,0.30,0.908610,0.236983,0.969444,0.800372,0.503019
0.80,0.20,0.932874,0.201478,0.973922,0.832084,0.921654
0.90,0.10,0.950342,0.161241,0.976528,0.862210,1.469855
0.95,0.05,0.960937,0.120014,0.980603,0.878604,2.120144
1.00,0.00,0.959740,0.053635,0.977735,0.876689,5.909800

In [26]:
results_scratio_det_sigma_min_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1).mean()

auc_score                     0.783218
non_abundant_over_abundant    0.333697
correct_sign_prop             0.886900
ks_D                          0.641922
w_distance                    1.399055
dtype: float64

In [27]:
results_scratio_det_sigma_min_per_run.groupby("metric").mean()

                                      value  run
metric
corr_auc_score_p                   0.860796  1.0
corr_correct_sign_prop_p           0.654036  1.0
corr_ks_D_p                        0.868239  1.0
corr_non_abundant_over_abundant_p -0.890065  1.0
corr_p_major_cluster_p             1.000000  1.0
corr_p_minor_cluster_p            -1.000000  1.0
corr_run_p                              NaN  1.0
corr_w_distance_p                  0.798842  1.0
mean_auc_score                     0.957006  1.0
mean_correct_sign_prop             0.978288  1.0
mean_ks_D                          0.872501  1.0
mean_non_abundant_over_abundant    0.111630  1.0
mean_p_major_cluster               0.950000  1.0
mean_p_minor_cluster               0.050000  1.0
mean_run                           1.000000  1.0
mean_w_distance                    3.166600  1.0
pearson_log_odds                   0.918133  1.0
spearman_log_odds                  0.876588  1.0

In [35]:
results_scratio_det_sigma_min_per_run.groupby("metric").std() / np.sqrt(3)

                                      value      run
metric
corr_auc_score_p                   0.001196  0.57735
corr_correct_sign_prop_p           0.021391  0.57735
corr_ks_D_p                        0.002078  0.57735
corr_non_abundant_over_abundant_p  0.006449  0.57735
corr_p_major_cluster_p             0.000000  0.57735
corr_p_minor_cluster_p             0.000000  0.57735
corr_run_p                              NaN  0.57735
corr_w_distance_p                  0.006258  0.57735
mean_auc_score                     0.000935  0.57735
mean_correct_sign_prop             0.000768  0.57735
mean_ks_D                          0.001923  0.57735
mean_non_abundant_over_abundant    0.004679  0.57735
mean_p_major_cluster               0.000000  0.57735
mean_p_minor_cluster               0.000000  0.57735
mean_run                           0.577350  0.57735
mean_w_distance                    0.023449  0.57735
pearson_log_odds                   0.002990  0.57735
spearman_log_odds                  0.009812  0.57735

## Stochastic sigma_min

In [28]:
scratio_stochastic_result_path = Path("/home/icb/alessandro.palma/environment/scFM_density_estimation/project_folder/results/abundance_test_experiment/scRatio/stochastic")
results_scratio_stochastic_per_oversamp, results_scratio_stochastic_per_run = compute_evaluation_metrics(scratio_stochastic_result_path, "scRatio", subsampling_rates, 3)

/ictstr01/home/icb/alessandro.palma/environment/scFM_density_estimation/notebooks/differential_abundance_analysis/model_evaluation.py:132: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  results_per_run["value"].append(sp.stats.pearsonr(results_per_oversamp_df_i[metric],

In [29]:
results_scratio_stochastic_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1)

,,auc_score,non_abundant_over_abundant,correct_sign_prop,ks_D,w_distance
p_major_cluster,p_minor_cluster,,,,,
0.50,0.50,0.313381,0.918067,0.464862,0.041152,0.007060
0.55,0.45,0.428171,0.671417,0.817574,0.218982,0.049497
0.60,0.40,0.664826,0.429020,0.928377,0.497830,0.172848
0.70,0.30,0.840800,0.298189,0.976056,0.724647,0.496356
0.80,0.20,0.927463,0.221385,0.983961,0.836501,0.905492
0.90,0.10,0.948477,0.181564,0.984871,0.863861,1.510910
0.95,0.05,0.955668,0.147110,0.984468,0.870115,2.147814
1.00,0.00,0.968459,0.058050,0.985221,0.888382,6.678609

In [30]:
results_scratio_stochastic_per_oversamp.groupby(["p_major_cluster", "p_minor_cluster"]).mean().drop("run", axis=1).mean(0)

auc_score                     0.755906
non_abundant_over_abundant    0.365600
correct_sign_prop             0.890674
ks_D                          0.617684
w_distance                    1.496073
dtype: float64

In [31]:
results_scratio_stochastic_per_run.groupby("metric").mean()

                                      value  run
metric
corr_auc_score_p                   0.910611  1.0
corr_correct_sign_prop_p           0.710255  1.0
corr_ks_D_p                        0.910213  1.0
corr_non_abundant_over_abundant_p -0.917125  1.0
corr_p_major_cluster_p             1.000000  1.0
corr_p_minor_cluster_p            -1.000000  1.0
corr_run_p                              NaN  1.0
corr_w_distance_p                  0.775966  1.0
mean_auc_score                     0.957535  1.0
mean_correct_sign_prop             0.984853  1.0
mean_ks_D                          0.874119  1.0
mean_non_abundant_over_abundant    0.128908  1.0
mean_p_major_cluster               0.950000  1.0
mean_p_minor_cluster               0.050000  1.0
mean_run                           1.000000  1.0
mean_w_distance                    3.445778  1.0
pearson_log_odds                   0.932359  1.0
spearman_log_odds                  0.868402  1.0

In [34]:
results_scratio_stochastic_per_run.groupby("metric").std() / np.sqrt(3)

                                      value      run
metric
corr_auc_score_p                   0.009823  0.57735
corr_correct_sign_prop_p           0.012579  0.57735
corr_ks_D_p                        0.008168  0.57735
corr_non_abundant_over_abundant_p  0.010344  0.57735
corr_p_major_cluster_p             0.000000  0.57735
corr_p_minor_cluster_p             0.000000  0.57735
corr_run_p                              NaN  0.57735
corr_w_distance_p                  0.001431  0.57735
mean_auc_score                     0.000810  0.57735
mean_correct_sign_prop             0.000299  0.57735
mean_ks_D                          0.002059  0.57735
mean_non_abundant_over_abundant    0.000520  0.57735
mean_p_major_cluster               0.000000  0.57735
mean_p_minor_cluster               0.000000  0.57735
mean_run                           0.577350  0.57735
mean_w_distance                    0.050167  0.57735
pearson_log_odds                   0.003666  0.57735
spearman_log_odds                  0.007622  0.57735

In [ ]:
x