In [1]:
import scipy as sp
import numpy as np
import pandas as pd
import pickle

pd.set_option('display.max_rows', None)

In [2]:
def mean_confidence_interval(x, confidence=0.95):
    m, se = np.mean(x), sp.stats.sem(x)
    h = se * sp.stats.t.ppf((1 + confidence) / 2., x.shape[0] - 1)
    return np.round(m - h, 2), np.round(m, 2), np.round(m + h, 2)

def preprocess_string(x):
    if x[0] != "-":
        for i, c in enumerate(x):
            if c.isalpha():
                break
    
        x = x[:i] + " " + x[i:]

        if x[0] == "0" and x[1] != ".":
            i = 1
        else:
            for i in range(1, len(x)):
                if (x[i - 1] == "1"):
                    break
        
        return x[:i] + " " + x[i:]
    else:
        return x

In [3]:
with open("./table_results/diff_results_time_uni_v2.pkl", "rb") as f:
    results = pickle.load(f)

mask_condition = results["mask_condition"]
mask_control = results["mask_control"]
mask_both = results["mask_both"]

In [4]:
keys = [x for x in results.keys() if "mask" not in x]
processed_results = {key: {e: [] for e in ["value", "time"]} for key in keys}

for key in keys:
    tmp_mean = np.mean(results[key]["value"][mask_condition], axis=0)
    processed_results[key]["value"] = mean_confidence_interval(tmp_mean)
    
    processed_results[key]["time"] = mean_confidence_interval(np.array(results[key]["time"]))

In [5]:
df = pd.DataFrame(processed_results).transpose()
df.reset_index(inplace=True)
# df["index"] = df["index"].apply(preprocess_string)

df["sigma_min"] = df["index"].apply(lambda x: x.split()[0])
df["sigma"] = df["index"].apply(lambda x: x.split()[1])
df["score_type"] = df["index"].apply(lambda x: x.split()[2])

df["value"] = df.value.apply(lambda x: np.round(np.array(x), 2))
df["time"] = df.time.apply(lambda x: np.round(np.array(x), 2))

df.drop("index", inplace=True, axis=1)
df = df[["sigma_min", "sigma", "score_type", "value", "time"]]
df.sort_values(["sigma_min", "sigma", "score_type"], ascending=False, inplace=True)
df

    sigma_min sigma score_type                  value                   time
4         0.1     1      rnlvf  [-13.3, 18.96, 51.22]  [52.75, 54.46, 56.17]
3         0.1     1        rnl  [22.63, 23.73, 24.83]  [13.45, 14.27, 15.09]
2         0.1     1         rl  [17.84, 18.84, 19.85]  [13.31, 14.37, 15.43]
1         0.1     1     direct   [21.3, 22.89, 24.49]   [33.47, 34.59, 35.7]
24        0.1  0.75      rnlvf   [-4.95, 17.58, 40.1]  [50.46, 52.43, 54.39]
23        0.1  0.75        rnl  [24.18, 25.28, 26.38]  [14.75, 15.61, 16.48]
22        0.1  0.75         rl  [19.39, 20.43, 21.47]   [14.74, 15.47, 16.2]
21        0.1  0.75     direct  [22.54, 24.19, 25.84]   [37.47, 38.1, 38.74]
44        0.1   0.5      rnlvf   [6.77, 10.19, 13.61]   [50.32, 51.8, 53.27]
43        0.1   0.5        rnl  [24.75, 26.08, 27.42]  [16.28, 17.51, 18.74]
42        0.1   0.5         rl   [18.72, 19.61, 20.5]   [16.87, 18.33, 19.8]
41        0.1   0.5     direct  [22.89, 24.56, 26.23]  [40.79, 42.16, 43.53]
64        0.1  0.25      rnlvf     [3.14, 8.62, 14.1]  [49.56, 51.05, 52.53]
63        0.1  0.25        rnl   [27.5, 29.52, 31.54]  [15.73, 17.33, 18.93]
62        0.1  0.25         rl   [19.77, 20.6, 21.42]  [18.66, 19.64, 20.61]
61        0.1  0.25     direct   [24.74, 28.22, 31.7]   [44.7, 45.48, 46.26]
84        0.1     0      rnlvf  [10.17, 11.89, 13.61]  [47.55, 48.72, 49.89]
83        0.1     0        rnl  [29.59, 33.92, 38.25]  [16.77, 17.98, 19.19]
82        0.1     0         rl   [20.0, 21.17, 22.34]  [19.14, 20.68, 22.22]
81        0.1     0     direct  [22.59, 27.31, 32.03]  [46.32, 47.19, 48.06]
8        0.01     1      rnlvf     [-7.14, 1.1, 9.35]  [63.25, 68.61, 73.97]
7        0.01     1        rnl  [23.03, 24.24, 25.46]   [15.46, 17.53, 19.6]
6        0.01     1         rl  [16.96, 17.79, 18.62]  [14.89, 16.37, 17.85]
5        0.01     1     direct  [20.31, 21.53, 22.74]  [40.28, 43.05, 45.82]
28       0.01  0.75      rnlvf    [-3.42, 7.79, 19.0]   [52.4, 54.65, 56.91]
27       0.01  0.75        rnl   [24.62, 26.21, 27.8]   [14.2, 15.49, 16.78]
26       0.01  0.75         rl  [17.84, 19.08, 20.33]   [16.5, 17.22, 17.94]
25       0.01  0.75     direct  [21.54, 23.38, 25.21]  [38.85, 39.69, 40.54]
48       0.01   0.5      rnlvf   [-1.68, 6.38, 14.44]  [52.36, 53.85, 55.33]
47       0.01   0.5        rnl  [24.43, 26.95, 29.48]  [16.23, 17.15, 18.06]
46       0.01   0.5         rl   [18.05, 19.5, 20.95]   [17.4, 18.58, 19.77]
45       0.01   0.5     direct  [20.13, 22.24, 24.36]  [42.35, 43.11, 43.88]
68       0.01  0.25      rnlvf    [4.11, 8.86, 13.61]  [50.28, 51.42, 52.56]
67       0.01  0.25        rnl     [30.1, 31.4, 32.7]  [14.79, 16.41, 18.03]
66       0.01  0.25         rl  [20.21, 20.87, 21.53]  [18.32, 19.52, 20.73]
65       0.01  0.25     direct   [22.2, 23.35, 24.51]   [44.8, 46.02, 47.24]
88       0.01     0      rnlvf    [8.71, 14.31, 19.9]   [34.74, 36.2, 37.65]
87       0.01     0        rnl   [41.49, 44.95, 48.4]  [14.09, 15.16, 16.23]
86       0.01     0         rl  [20.99, 21.84, 22.68]   [20.3, 21.46, 22.63]
85       0.01     0     direct  [24.62, 27.25, 29.89]  [48.63, 49.44, 50.25]
12      0.001     1      rnlvf    [1.08, 8.37, 15.67]  [64.25, 74.06, 83.87]
11      0.001     1        rnl  [21.74, 23.54, 25.34]  [12.34, 15.66, 18.97]
10      0.001     1         rl   [15.79, 16.7, 17.62]  [15.05, 16.25, 17.44]
9       0.001     1     direct  [18.35, 20.25, 22.15]   [36.85, 41.43, 46.0]
32      0.001  0.75      rnlvf   [5.55, 14.62, 23.68]  [57.71, 59.89, 62.08]
31      0.001  0.75        rnl   [22.75, 24.3, 25.84]  [15.75, 16.23, 16.71]
30      0.001  0.75         rl  [17.49, 18.11, 18.73]  [16.09, 17.48, 18.86]
29      0.001  0.75     direct  [19.39, 20.68, 21.96]  [39.81, 40.38, 40.95]
52      0.001   0.5      rnlvf   [-8.08, 5.14, 18.36]  [54.22, 55.94, 57.66]
51      0.001   0.5        rnl   [23.29, 25.05, 26.8]  [15.69, 16.97, 18.25]
50      0.001   0.5         rl  [16.54, 17.77, 18.99]  [18.43, 19.65, 20.88]
49      0.001   0.5     direct  [18.61, 19.79, 20.97]    [42.0, 43.2, 44.39]
72      0.001  0.25      rnlvf   [7.79, 11.05, 14.31]  [51.73, 52.97, 54.21]
71      0.001  0.25        rnl  [26.54, 29.05, 31.56]  [16.65, 17.59, 18.53]
70      0.001  0.25         rl  [18.92, 20.05, 21.17]  [21.28, 22.56, 23.85]
69      0.001  0.25     direct  [20.82, 22.88, 24.94]  [44.98, 46.17, 47.36]
92      0.001     0      rnlvf  [11.41, 16.43, 21.44]   [34.75, 36.68, 38.6]
91      0.001     0        rnl   [48.88, 55.0, 61.12]   [14.5, 15.47, 16.44]
90      0.001     0         rl  [21.07, 22.05, 23.03]   [20.68, 22.1, 23.52]
89      0.001     0     direct  [22.28, 24.72, 27.16]  [48.51, 49.86, 51.22]
16     0.0001     1      rnlvf    [2.54, 11.67, 20.8]  [61.17, 63.54, 65.91]
15     0.0001     1        rnl  [21.67, 22.94, 24.21]  [14.02, 15.48, 16.95]
14     0.0001     1         rl   [15.69, 16.65, 17.6]  [14.93, 16.12, 17.32]
13     0.0001     1     direct   [17.81, 19.26, 20.7]  [35.35, 38.03, 40.71]
36     0.0001  0.75      rnlvf    [5.92, 11.6, 17.29]  [59.99, 63.38, 66.78]
35     0.0001  0.75        rnl   [22.3, 23.76, 25.23]     [14.5, 16.1, 17.7]
34     0.0001  0.75         rl  [17.04, 17.86, 18.68]    [17.2, 18.5, 19.81]
33     0.0001  0.75     direct   [18.7, 19.43, 20.15]  [40.25, 40.79, 41.33]
56     0.0001   0.5      rnlvf    [7.02, 13.2, 19.38]   [56.2, 59.49, 62.77]
55     0.0001   0.5        rnl   [22.75, 24.9, 27.05]  [16.46, 17.75, 19.03]
54     0.0001   0.5         rl  [17.48, 18.25, 19.02]   [19.8, 20.74, 21.69]
53     0.0001   0.5     direct  [18.54, 19.72, 20.91]   [42.7, 43.71, 44.73]
76     0.0001  0.25      rnlvf   [-1.44, 6.77, 14.99]   [50.4, 52.58, 54.75]
75     0.0001  0.25        rnl   [28.55, 30.1, 31.66]   [16.68, 17.74, 18.8]
74     0.0001  0.25         rl  [19.35, 20.23, 21.11]   [19.8, 20.99, 22.18]
73     0.0001  0.25     direct  [20.46, 21.78, 23.09]  [44.88, 46.33, 47.77]
96     0.0001     0      rnlvf   [8.25, 10.88, 13.51]  [34.98, 36.53, 38.09]
95     0.0001     0        rnl   [54.4, 63.26, 72.13]   [12.58, 14.09, 15.6]
94     0.0001     0         rl    [20.6, 21.5, 22.39]  [20.51, 22.21, 23.92]
93     0.0001     0     direct  [22.04, 24.91, 27.79]  [48.43, 49.44, 50.44]
20          0     1      rnlvf     [-3.15, 3.4, 9.94]  [61.51, 64.15, 66.78]
19          0     1        rnl  [21.94, 23.65, 25.35]  [13.86, 15.37, 16.88]
18          0     1         rl   [16.25, 17.03, 17.8]  [15.61, 16.76, 17.91]
17          0     1     direct   [18.51, 19.9, 21.28]  [35.71, 37.03, 38.34]
40          0  0.75      rnlvf   [4.07, 15.41, 26.74]  [59.69, 61.77, 63.85]
39          0  0.75        rnl  [22.49, 23.92, 25.35]  [15.31, 16.39, 17.46]
38          0  0.75         rl  [16.79, 17.57, 18.35]  [16.81, 18.02, 19.24]
37          0  0.75     direct  [18.72, 19.52, 20.33]   [39.62, 40.3, 40.98]
60          0   0.5      rnlvf    [6.45, 11.27, 16.1]  [54.66, 56.87, 59.09]
59          0   0.5        rnl  [22.62, 25.49, 28.35]   [17.58, 18.94, 20.3]
58          0   0.5         rl  [17.33, 18.77, 20.22]   [18.42, 19.8, 21.19]
57          0   0.5     direct  [18.35, 20.08, 21.81]  [42.44, 43.85, 45.27]
80          0  0.25      rnlvf   [6.39, 10.86, 15.34]   [51.1, 53.18, 55.25]
79          0  0.25        rnl  [26.73, 30.03, 33.32]  [16.26, 17.27, 18.29]
78          0  0.25         rl   [19.09, 20.25, 21.4]   [19.74, 21.27, 22.8]
77          0  0.25     direct  [20.45, 21.91, 23.37]   [45.2, 46.39, 47.57]
100         0     0      rnlvf   [9.59, 11.33, 13.08]  [34.45, 35.49, 36.54]
99          0     0        rnl  [50.65, 58.06, 65.48]  [12.55, 13.92, 15.29]
98          0     0         rl   [21.36, 22.4, 23.43]  [20.95, 22.11, 23.27]
97          0     0     direct  [23.99, 25.83, 27.67]  [47.84, 49.14, 50.43]
0           -     -       true     [20.1, 20.1, 20.1]     [0.01, 0.02, 0.02]

In [6]:
group = df.groupby(["score_type"])[["value", "time"]].mean().reset_index()
group["value"] = group.value.apply(lambda x: np.round(np.array(x), 2))
group["time"] = group.time.apply(lambda x: np.round(np.array(x), 2))
group

  score_type                  value                   time
0     direct   [20.8, 22.62, 24.45]    [42.09, 43.4, 44.7]
1         rl   [18.42, 19.4, 20.37]  [17.82, 19.05, 20.28]
2        rnl  [28.38, 31.01, 33.64]  [15.06, 16.38, 17.69]
3      rnlvf   [2.63, 10.71, 18.78]  [51.62, 53.99, 56.36]
4       true     [20.1, 20.1, 20.1]     [0.01, 0.02, 0.02]

In [7]:
true = np.array([20.1, 20.1, 20.1])

In [8]:
group = df.copy()
group["value"] = group.value.apply(lambda x: x - true)
group = group.groupby(["sigma_min", "score_type"])[["value", "time"]].mean().reset_index()
group["value"] = group.value.apply(lambda x: np.round(np.array(x), 2))
group["time"] = group.time.apply(lambda x: np.round(np.array(x), 2))
group.sort_values(["sigma_min", "score_type"], ascending=False, inplace=True)
group

   sigma_min score_type                    value                   time
20       0.1      rnlvf    [-19.73, -6.65, 6.43]  [50.13, 51.69, 53.25]
19       0.1        rnl       [5.63, 7.61, 9.58]   [15.4, 16.54, 17.69]
18       0.1         rl      [-0.96, 0.03, 1.02]   [16.54, 17.7, 18.85]
17       0.1     direct       [2.71, 5.33, 7.96]   [40.55, 41.5, 42.46]
16      0.01      rnlvf  [-19.98, -12.41, -4.84]  [50.61, 52.95, 55.28]
15      0.01        rnl     [8.63, 10.65, 12.67]  [14.95, 16.35, 17.74]
14      0.01         rl     [-1.29, -0.28, 0.72]  [17.48, 18.63, 19.78]
13      0.01     direct       [1.66, 3.45, 5.24]  [42.98, 44.26, 45.55]
12     0.001      rnlvf   [-16.55, -8.98, -1.41]  [52.53, 55.91, 59.28]
11     0.001        rnl     [8.54, 11.29, 14.03]  [14.99, 16.38, 17.78]
10     0.001         rl    [-2.14, -1.16, -0.19]  [18.31, 19.61, 20.91]
9      0.001     direct      [-0.21, 1.56, 3.34]  [42.43, 44.21, 45.98]
8     0.0001      rnlvf   [-15.64, -9.28, -2.91]   [52.55, 55.1, 57.66]
7     0.0001        rnl     [9.83, 12.89, 15.96]  [14.85, 16.23, 17.62]
6     0.0001         rl     [-2.07, -1.2, -0.34]  [18.45, 19.71, 20.98]
5     0.0001     direct      [-0.59, 0.92, 2.43]   [42.32, 43.66, 45.0]
4          0      rnlvf   [-15.43, -9.65, -3.86]   [52.28, 54.29, 56.3]
3          0        rnl     [8.79, 12.13, 15.47]  [15.11, 16.38, 17.64]
2          0         rl      [-1.94, -0.9, 0.14]  [18.31, 19.59, 20.88]
1          0     direct       [-0.1, 1.35, 2.79]  [42.16, 43.34, 44.52]
0          -       true          [0.0, 0.0, 0.0]     [0.01, 0.02, 0.02]

In [9]:
group = df.copy()
group["value"] = group.value.apply(lambda x: x - true)
group = group.groupby(["sigma", "score_type"])[["value", "time"]].mean().reset_index()
group["value"] = group.value.apply(lambda x: np.round(np.array(x), 2))
group["time"] = group.time.apply(lambda x: np.round(np.array(x), 2))
group.sort_values(["sigma", "score_type"], ascending=False, inplace=True)
group

   sigma score_type                   value                   time
20     1      rnlvf    [-24.09, -11.4, 1.3]  [60.59, 64.96, 69.34]
19     1        rnl       [2.1, 3.52, 4.94]   [13.83, 15.66, 17.5]
18     1         rl     [-3.59, -2.7, -1.8]  [14.76, 15.97, 17.19]
17     1     direct     [-0.84, 0.67, 2.17]  [36.33, 38.83, 41.31]
16  0.75      rnlvf    [-18.67, -6.7, 5.26]   [56.05, 58.42, 60.8]
15  0.75        rnl      [3.17, 4.59, 6.02]   [14.9, 15.96, 17.03]
14  0.75         rl   [-2.39, -1.49, -0.59]  [16.27, 17.34, 18.41]
13  0.75     direct       [0.08, 1.34, 2.6]   [39.2, 39.85, 40.51]
12   0.5      rnlvf  [-18.0, -10.86, -3.72]  [53.55, 55.59, 57.62]
11   0.5        rnl      [3.47, 5.59, 7.72]  [16.45, 17.66, 18.88]
10   0.5         rl   [-2.48, -1.32, -0.16]  [18.18, 19.42, 20.67]
9    0.5     direct      [-0.4, 1.18, 2.76]  [42.06, 43.21, 44.36]
8   0.25      rnlvf  [-16.1, -10.87, -5.63]  [50.61, 52.24, 53.86]
7   0.25        rnl     [7.78, 9.92, 12.06]  [16.02, 17.27, 18.52]
6   0.25         rl      [-0.63, 0.3, 1.23]   [19.56, 20.8, 22.03]
5   0.25     direct      [1.63, 3.53, 5.42]  [44.91, 46.08, 47.24]
4      0      rnlvf  [-10.47, -7.13, -3.79]  [37.29, 38.72, 40.15]
3      0        rnl    [24.9, 30.94, 36.98]   [14.1, 15.32, 16.55]
2      0         rl       [0.7, 1.69, 2.67]  [20.32, 21.71, 23.11]
1      0     direct        [3.0, 5.9, 8.81]  [47.95, 49.01, 50.08]
0      -       true         [0.0, 0.0, 0.0]     [0.01, 0.02, 0.02]

In [10]:
df["diff_mean"] = df.value.apply(lambda x: x[1] - true[0])
df["diff_mean_abs"] = df.diff_mean.apply(abs)
df.sort_values("diff_mean_abs")

,sigma_min,sigma,score_type,value,time,diff_mean,diff_mean_abs
0,-,-,true,"[20.1, 20.1, 20.1]","[0.01, 0.02, 0.02]",0.00,0.00
57,0,0.5,direct,"[18.35, 20.08, 21.81]","[42.44, 43.85, 45.27]",-0.02,0.02
70,0.001,0.25,rl,"[18.92, 20.05, 21.17]","[21.28, 22.56, 23.85]",-0.05,0.05
74,0.0001,0.25,rl,"[19.35, 20.23, 21.11]","[19.8, 20.99, 22.18]",0.13,0.13
78,0,0.25,rl,"[19.09, 20.25, 21.4]","[19.74, 21.27, 22.8]",0.15,0.15
9,0.001,1,direct,"[18.35, 20.25, 22.15]","[36.85, 41.43, 46.0]",0.15,0.15
17,0,1,direct,"[18.51, 19.9, 21.28]","[35.71, 37.03, 38.34]",-0.20,0.20
49,0.001,0.5,direct,"[18.61, 19.79, 20.97]","[42.0, 43.2, 44.39]",-0.31,0.31
22,0.1,0.75,rl,"[19.39, 20.43, 21.47]","[14.74, 15.47, 16.2]",0.33,0.33
53,0.0001,0.5,direct,"[18.54, 19.72, 20.91]","[42.7, 43.71, 44.73]",-0.38,0.38
42,0.1,0.5,rl,"[18.72, 19.61, 20.5]","[16.87, 18.33, 19.8]",-0.49,0.49
62,0.1,0.25,rl,"[19.77, 20.6, 21.42]","[18.66, 19.64, 20.61]",0.50,0.50
29,0.001,0.75,direct,"[19.39, 20.68, 21.96]","[39.81, 40.38, 40.95]",0.58,0.58
37,0,0.75,direct,"[18.72, 19.52, 20.33]","[39.62, 40.3, 40.98]",-0.58,0.58
46,0.01,0.5,rl,"[18.05, 19.5, 20.95]","[17.4, 18.58, 19.77]",-0.60,0.60
33,0.0001,0.75,direct,"[18.7, 19.43, 20.15]","[40.25, 40.79, 41.33]",-0.67,0.67
66,0.01,0.25,rl,"[20.21, 20.87, 21.53]","[18.32, 19.52, 20.73]",0.77,0.77
13,0.0001,1,direct,"[17.81, 19.26, 20.7]","[35.35, 38.03, 40.71]",-0.84,0.84
26,0.01,0.75,rl,"[17.84, 19.08, 20.33]","[16.5, 17.22, 17.94]",-1.02,1.02
82,0.1,0,rl,"[20.0, 21.17, 22.34]","[19.14, 20.68, 22.22]",1.07,1.07
4,0.1,1,rnlvf,"[-13.3, 18.96, 51.22]","[52.75, 54.46, 56.17]",-1.14,1.14
2,0.1,1,rl,"[17.84, 18.84, 19.85]","[13.31, 14.37, 15.43]",-1.26,1.26
58,0,0.5,rl,"[17.33, 18.77, 20.22]","[18.42, 19.8, 21.19]",-1.33,1.33
94,0.0001,0,rl,"[20.6, 21.5, 22.39]","[20.51, 22.21, 23.92]",1.40,1.40
5,0.01,1,direct,"[20.31, 21.53, 22.74]","[40.28, 43.05, 45.82]",1.43,1.43
73,0.0001,0.25,direct,"[20.46, 21.78, 23.09]","[44.88, 46.33, 47.77]",1.68,1.68
86,0.01,0,rl,"[20.99, 21.84, 22.68]","[20.3, 21.46, 22.63]",1.74,1.74
77,0,0.25,direct,"[20.45, 21.91, 23.37]","[45.2, 46.39, 47.57]",1.81,1.81
54,0.0001,0.5,rl,"[17.48, 18.25, 19.02]","[19.8, 20.74, 21.69]",-1.85,1.85
90,0.001,0,rl,"[21.07, 22.05, 23.03]","[20.68, 22.1, 23.52]",1.95,1.95
30,0.001,0.75,rl,"[17.49, 18.11, 18.73]","[16.09, 17.48, 18.86]",-1.99,1.99
45,0.01,0.5,direct,"[20.13, 22.24, 24.36]","[42.35, 43.11, 43.88]",2.14,2.14
34,0.0001,0.75,rl,"[17.04, 17.86, 18.68]","[17.2, 18.5, 19.81]",-2.24,2.24
98,0,0,rl,"[21.36, 22.4, 23.43]","[20.95, 22.11, 23.27]",2.30,2.30
6,0.01,1,rl,"[16.96, 17.79, 18.62]","[14.89, 16.37, 17.85]",-2.31,2.31
50,0.001,0.5,rl,"[16.54, 17.77, 18.99]","[18.43, 19.65, 20.88]",-2.33,2.33
24,0.1,0.75,rnlvf,"[-4.95, 17.58, 40.1]","[50.46, 52.43, 54.39]",-2.52,2.52
38,0,0.75,rl,"[16.79, 17.57, 18.35]","[16.81, 18.02, 19.24]",-2.53,2.53
69,0.001,0.25,direct,"[20.82, 22.88, 24.94]","[44.98, 46.17, 47.36]",2.78,2.78
1,0.1,1,direct,"[21.3, 22.89, 24.49]","[33.47, 34.59, 35.7]",2.79,2.79
15,0.0001,1,rnl,"[21.67, 22.94, 24.21]","[14.02, 15.48, 16.95]",2.84,2.84
18,0,1,rl,"[16.25, 17.03, 17.8]","[15.61, 16.76, 17.91]",-3.07,3.07
65,0.01,0.25,direct,"[22.2, 23.35, 24.51]","[44.8, 46.02, 47.24]",3.25,3.25
25,0.01,0.75,direct,"[21.54, 23.38, 25.21]","[38.85, 39.69, 40.54]",3.28,3.28
10,0.001,1,rl,"[15.79, 16.7, 17.62]","[15.05, 16.25, 17.44]",-3.40,3.40
11,0.001,1,rnl,"[21.74, 23.54, 25.34]","[12.34, 15.66, 18.97]",3.44,3.44
14,0.0001,1,rl,"[15.69, 16.65, 17.6]","[14.93, 16.12, 17.32]",-3.45,3.45
19,0,1,rnl,"[21.94, 23.65, 25.35]","[13.86, 15.37, 16.88]",3.55,3.55
3,0.1,1,rnl,"[22.63, 23.73, 24.83]","[13.45, 14.27, 15.09]",3.63,3.63
35,0.0001,0.75,rnl,"[22.3, 23.76, 25.23]","[14.5, 16.1, 17.7]",3.66,3.66
92,0.001,0,rnlvf,"[11.41, 16.43, 21.44]","[34.75, 36.68, 38.6]",-3.67,3.67
39,0,0.75,rnl,"[22.49, 23.92, 25.35]","[15.31, 16.39, 17.46]",3.82,3.82
21,0.1,0.75,direct,"[22.54, 24.19, 25.84]","[37.47, 38.1, 38.74]",4.09,4.09
7,0.01,1,rnl,"[23.03, 24.24, 25.46]","[15.46, 17.53, 19.6]",4.14,4.14
31,0.001,0.75,rnl,"[22.75, 24.3, 25.84]","[15.75, 16.23, 16.71]",4.20,4.20
41,0.1,0.5,direct,"[22.89, 24.56, 26.23]","[40.79, 42.16, 43.53]",4.46,4.46
89,0.001,0,direct,"[22.28, 24.72, 27.16]","[48.51, 49.86, 51.22]",4.62,4.62
40,0,0.75,rnlvf,"[4.07, 15.41, 26.74]","[59.69, 61.77, 63.85]",-4.69,4.69
55,0.0001,0.5,rnl,"[22.75, 24.9, 27.05]","[16.46, 17.75, 19.03]",4.80,4.80
93,0.0001,0,direct,"[22.04, 24.91, 27.79]","[48.43, 49.44, 50.44]",4.81,4.81
51,0.001,0.5,rnl,"[23.29, 25.05, 26.8]","[15.69, 16.97, 18.25]",4.95,4.95
23,0.1,0.75,rnl,"[24.18, 25.28, 26.38]","[14.75, 15.61, 16.48]",5.18,5.18
59,0,0.5,rnl,"[22.62, 25.49, 28.35]","[17.58, 18.94, 20.3]",5.39,5.39
32,0.001,0.75,rnlvf,"[5.55, 14.62, 23.68]","[57.71, 59.89, 62.08]",-5.48,5.48
97,0,0,direct,"[23.99, 25.83, 27.67]","[47.84, 49.14, 50.43]",5.73,5.73
88,0.01,0,rnlvf,"[8.71, 14.31, 19.9]","[34.74, 36.2, 37.65]",-5.79,5.79
43,0.1,0.5,rnl,"[24.75, 26.08, 27.42]","[16.28, 17.51, 18.74]",5.98,5.98
27,0.01,0.75,rnl,"[24.62, 26.21, 27.8]","[14.2, 15.49, 16.78]",6.11,6.11
47,0.01,0.5,rnl,"[24.43, 26.95, 29.48]","[16.23, 17.15, 18.06]",6.85,6.85
56,0.0001,0.5,rnlvf,"[7.02, 13.2, 19.38]","[56.2, 59.49, 62.77]",-6.90,6.90
85,0.01,0,direct,"[24.62, 27.25, 29.89]","[48.63, 49.44, 50.25]",7.15,7.15
81,0.1,0,direct,"[22.59, 27.31, 32.03]","[46.32, 47.19, 48.06]",7.21,7.21
61,0.1,0.25,direct,"[24.74, 28.22, 31.7]","[44.7, 45.48, 46.26]",8.12,8.12
84,0.1,0,rnlvf,"[10.17, 11.89, 13.61]","[47.55, 48.72, 49.89]",-8.21,8.21
16,0.0001,1,rnlvf,"[2.54, 11.67, 20.8]","[61.17, 63.54, 65.91]",-8.43,8.43
36,0.0001,0.75,rnlvf,"[5.92, 11.6, 17.29]","[59.99, 63.38, 66.78]",-8.50,8.50
100,0,0,rnlvf,"[9.59, 11.33, 13.08]","[34.45, 35.49, 36.54]",-8.77,8.77
60,0,0.5,rnlvf,"[6.45, 11.27, 16.1]","[54.66, 56.87, 59.09]",-8.83,8.83
71,0.001,0.25,rnl,"[26.54, 29.05, 31.56]","[16.65, 17.59, 18.53]",8.95,8.95
72,0.001,0.25,rnlvf,"[7.79, 11.05, 14.31]","[51.73, 52.97, 54.21]",-9.05,9.05
96,0.0001,0,rnlvf,"[8.25, 10.88, 13.51]","[34.98, 36.53, 38.09]",-9.22,9.22
80,0,0.25,rnlvf,"[6.39, 10.86, 15.34]","[51.1, 53.18, 55.25]",-9.24,9.24
63,0.1,0.25,rnl,"[27.5, 29.52, 31.54]","[15.73, 17.33, 18.93]",9.42,9.42
44,0.1,0.5,rnlvf,"[6.77, 10.19, 13.61]","[50.32, 51.8, 53.27]",-9.91,9.91
79,0,0.25,rnl,"[26.73, 30.03, 33.32]","[16.26, 17.27, 18.29]",9.93,9.93
75,0.0001,0.25,rnl,"[28.55, 30.1, 31.66]","[16.68, 17.74, 18.8]",10.00,10.00
68,0.01,0.25,rnlvf,"[4.11, 8.86, 13.61]","[50.28, 51.42, 52.56]",-11.24,11.24
67,0.01,0.25,rnl,"[30.1, 31.4, 32.7]","[14.79, 16.41, 18.03]",11.30,11.30
64,0.1,0.25,rnlvf,"[3.14, 8.62, 14.1]","[49.56, 51.05, 52.53]",-11.48,11.48
12,0.001,1,rnlvf,"[1.08, 8.37, 15.67]","[64.25, 74.06, 83.87]",-11.73,11.73
28,0.01,0.75,rnlvf,"[-3.42, 7.79, 19.0]","[52.4, 54.65, 56.91]",-12.31,12.31
76,0.0001,0.25,rnlvf,"[-1.44, 6.77, 14.99]","[50.4, 52.58, 54.75]",-13.33,13.33
48,0.01,0.5,rnlvf,"[-1.68, 6.38, 14.44]","[52.36, 53.85, 55.33]",-13.72,13.72
83,0.1,0,rnl,"[29.59, 33.92, 38.25]","[16.77, 17.98, 19.19]",13.82,13.82
52,0.001,0.5,rnlvf,"[-8.08, 5.14, 18.36]","[54.22, 55.94, 57.66]",-14.96,14.96
20,0,1,rnlvf,"[-3.15, 3.4, 9.94]","[61.51, 64.15, 66.78]",-16.70,16.70
8,0.01,1,rnlvf,"[-7.14, 1.1, 9.35]","[63.25, 68.61, 73.97]",-19.00,19.00
87,0.01,0,rnl,"[41.49, 44.95, 48.4]","[14.09, 15.16, 16.23]",24.85,24.85
91,0.001,0,rnl,"[48.88, 55.0, 61.12]","[14.5, 15.47, 16.44]",34.90,34.90
99,0,0,rnl,"[50.65, 58.06, 65.48]","[12.55, 13.92, 15.29]",37.96,37.96
95,0.0001,0,rnl,"[54.4, 63.26, 72.13]","[12.58, 14.09, 15.6]",43.16,43.16