In [18]:
import scipy as sp
import numpy as np
import pandas as pd
import pickle

In [2]:
def mean_confidence_interval(x, confidence=0.95):
    m, se = np.mean(x), sp.stats.sem(x)
    h = se * sp.stats.t.ppf((1 + confidence) / 2., x.shape[0] - 1)
    return np.round(m - h, 2), np.round(m, 2), np.round(m + h, 2)

In [27]:
with open("./table_results/really_easy_results_all.pkl", "rb") as f:
    results = pickle.load(f)

mask_condition = results["mask_condition"]
mask_control = results["mask_control"]
mask_both = results["mask_both"]

In [28]:
names = ["true", "direct", "ct own"]
sigmas = [x for x in results.keys() if "mask" not in x]
processed_results = {e: {sigma: {name: np.array([]) for name in names} for sigma in sigmas} for e in ["sum", "mean"]}

for sigma in sigmas:
    for name in names:
        tmp_sum = np.sum(results[sigma][name][mask_condition], axis=0)
        tmp_mean = np.mean(results[sigma][name][mask_condition], axis=0)
        
        processed_results["sum"][sigma][name] = mean_confidence_interval(tmp_sum)
        processed_results["mean"][sigma][name] = mean_confidence_interval(tmp_mean)

In [29]:
df_mean = pd.DataFrame(processed_results["mean"]).transpose()
df_mean

,true,direct,ct own
0.1 orig,"(4.99, 4.99, 4.99)","(4.9, 5.16, 5.42)","(5.23, 5.65, 6.07)"
0.01 orig,"(4.99, 4.99, 4.99)","(5.53, 5.79, 6.06)","(6.54, 7.07, 7.61)"
0.001 orig,"(4.99, 4.99, 4.99)","(5.06, 5.4, 5.75)","(6.44, 7.08, 7.73)"
0.0001 orig,"(4.99, 4.99, 4.99)","(5.1, 5.37, 5.64)","(6.74, 7.39, 8.04)"
0 orig,"(4.99, 4.99, 4.99)","(5.13, 5.46, 5.79)","(5.95, 6.41, 6.86)"
0 pure tong,"(4.99, 4.99, 4.99)","(4.71, 5.27, 5.83)","(2.26, 2.44, 2.62)"
0 our own way,"(4.99, 4.99, 4.99)","(5.08, 5.42, 5.75)","(5.3, 5.55, 5.8)"
0.1 orig + tong,"(4.99, 4.99, 4.99)","(4.76, 5.27, 5.78)","(11.8, 12.87, 13.93)"
0.01 orig + tong,"(4.99, 4.99, 4.99)","(4.61, 5.28, 5.96)","(18.01, 20.85, 23.7)"
0.001 orig + tong,"(4.99, 4.99, 4.99)","(4.83, 5.31, 5.8)","(28.73, 32.48, 36.24)"
0.0001 orig + tong,"(4.99, 4.99, 4.99)","(4.86, 5.21, 5.56)","(39.6, 42.15, 44.69)"
0 orig + tong,"(4.99, 4.99, 4.99)","(4.84, 5.45, 6.06)","(19.93, 22.47, 25.02)"
0 tong + ours,"(4.99, 4.99, 4.99)","(4.87, 5.58, 6.3)","(14.15, 15.63, 17.1)"

In [22]:
# difficult example
df_mean

,true,direct,ct own
0.1 orig,"(20.27, 20.27, 20.27)","(25.14, 28.34, 31.53)","(32.16, 34.43, 36.69)"
0.01 orig,"(20.27, 20.27, 20.27)","(23.91, 25.82, 27.73)","(43.49, 46.65, 49.82)"
0.001 orig,"(20.27, 20.27, 20.27)","(24.01, 25.8, 27.58)","(53.05, 59.15, 65.25)"
0.0001 orig,"(20.27, 20.27, 20.27)","(23.74, 27.94, 32.14)","(66.18, 76.75, 87.32)"
0 orig,"(20.27, 20.27, 20.27)","(23.82, 26.07, 28.33)","(42.19, 46.7, 51.2)"
0 pure tong,"(20.27, 20.27, 20.27)","(17.95, 19.46, 20.97)","(8.25, 8.7, 9.16)"
0 our own way,"(20.27, 20.27, 20.27)","(22.77, 24.03, 25.29)","(20.24, 21.61, 22.97)"
0.1 orig + tong,"(20.27, 20.27, 20.27)","(17.38, 19.48, 21.58)","(49.1, 54.11, 59.11)"
0.01 orig + tong,"(20.27, 20.27, 20.27)","(19.5, 21.28, 23.05)","(92.66, 100.85, 109.05)"
0.001 orig + tong,"(20.27, 20.27, 20.27)","(14.84, 17.98, 21.11)","(103.87, 128.96, 154.05)"
0.0001 orig + tong,"(20.27, 20.27, 20.27)","(17.39, 19.76, 22.13)","(152.12, 186.0, 219.88)"
0 orig + tong,"(20.27, 20.27, 20.27)","(17.07, 19.45, 21.83)","(82.63, 93.03, 103.44)"
0 tong + ours,"(20.27, 20.27, 20.27)","(19.81, 21.49, 23.17)","(66.88, 75.42, 83.96)"

In [26]:
# "easy" example
df_mean

,true,direct,ct own
0.1 orig,"(20.0, 20.0, 20.0)","(21.38, 22.61, 23.85)","(26.68, 27.95, 29.23)"
0.01 orig,"(20.0, 20.0, 20.0)","(20.88, 21.91, 22.93)","(33.5, 36.11, 38.72)"
0.001 orig,"(20.0, 20.0, 20.0)","(22.53, 23.96, 25.38)","(40.16, 45.25, 50.33)"
0.0001 orig,"(20.0, 20.0, 20.0)","(21.11, 22.0, 22.89)","(46.46, 49.19, 51.93)"
0 orig,"(20.0, 20.0, 20.0)","(20.65, 22.41, 24.16)","(32.33, 35.8, 39.28)"
0 pure tong,"(20.0, 20.0, 20.0)","(17.12, 18.27, 19.42)","(7.83, 8.38, 8.93)"
0 our own way,"(20.0, 20.0, 20.0)","(20.94, 22.92, 24.9)","(20.78, 21.48, 22.18)"
0.1 orig + tong,"(20.0, 20.0, 20.0)","(16.98, 18.45, 19.92)","(44.25, 48.73, 53.2)"
0.01 orig + tong,"(20.0, 20.0, 20.0)","(17.22, 18.26, 19.31)","(79.03, 86.09, 93.15)"
0.001 orig + tong,"(20.0, 20.0, 20.0)","(17.95, 19.71, 21.46)","(119.7, 135.17, 150.65)"
0.0001 orig + tong,"(20.0, 20.0, 20.0)","(17.27, 18.76, 20.25)","(141.7, 171.68, 201.65)"
0 orig + tong,"(20.0, 20.0, 20.0)","(17.17, 19.46, 21.76)","(77.94, 86.96, 95.97)"
0 tong + ours,"(20.0, 20.0, 20.0)","(17.42, 18.29, 19.17)","(63.6, 69.88, 76.16)"

In [30]:
# really easy example
df_mean

,true,direct,ct own
0.1 orig,"(4.99, 4.99, 4.99)","(4.9, 5.16, 5.42)","(5.23, 5.65, 6.07)"
0.01 orig,"(4.99, 4.99, 4.99)","(5.53, 5.79, 6.06)","(6.54, 7.07, 7.61)"
0.001 orig,"(4.99, 4.99, 4.99)","(5.06, 5.4, 5.75)","(6.44, 7.08, 7.73)"
0.0001 orig,"(4.99, 4.99, 4.99)","(5.1, 5.37, 5.64)","(6.74, 7.39, 8.04)"
0 orig,"(4.99, 4.99, 4.99)","(5.13, 5.46, 5.79)","(5.95, 6.41, 6.86)"
0 pure tong,"(4.99, 4.99, 4.99)","(4.71, 5.27, 5.83)","(2.26, 2.44, 2.62)"
0 our own way,"(4.99, 4.99, 4.99)","(5.08, 5.42, 5.75)","(5.3, 5.55, 5.8)"
0.1 orig + tong,"(4.99, 4.99, 4.99)","(4.76, 5.27, 5.78)","(11.8, 12.87, 13.93)"
0.01 orig + tong,"(4.99, 4.99, 4.99)","(4.61, 5.28, 5.96)","(18.01, 20.85, 23.7)"
0.001 orig + tong,"(4.99, 4.99, 4.99)","(4.83, 5.31, 5.8)","(28.73, 32.48, 36.24)"
0.0001 orig + tong,"(4.99, 4.99, 4.99)","(4.86, 5.21, 5.56)","(39.6, 42.15, 44.69)"
0 orig + tong,"(4.99, 4.99, 4.99)","(4.84, 5.45, 6.06)","(19.93, 22.47, 25.02)"
0 tong + ours,"(4.99, 4.99, 4.99)","(4.87, 5.58, 6.3)","(14.15, 15.63, 17.1)"