In [1]:
import scipy as sp
import numpy as np
import pandas as pd
import pickle

In [2]:
def mean_confidence_interval(x, confidence=0.95):
    m, se = np.mean(x), sp.stats.sem(x)
    h = se * sp.stats.t.ppf((1 + confidence) / 2., x.shape[0] - 1)
    return np.round(m - h, 2), np.round(m, 2), np.round(m + h, 2)

In [18]:
with open("./table_results/really_easy_results_time_v2.pkl", "rb") as f:
    results = pickle.load(f)

mask_condition = results["mask_condition"]
mask_control = results["mask_control"]
mask_both = results["mask_both"]

In [19]:
keys = [x for x in results.keys() if "mask" not in x]
processed_results = {key: {e: [] for e in ["value", "time"]} for key in keys}

for key in keys:
    tmp_mean = np.mean(results[key]["value"][mask_condition], axis=0)
    processed_results[key]["value"] = mean_confidence_interval(tmp_mean)
    
    processed_results[key]["time"] = mean_confidence_interval(np.array(results[key]["time"]))

In [20]:
df = pd.DataFrame(processed_results).transpose()
df.reset_index(inplace=True)
df["sigma_min"] = df["index"].apply(lambda x: x.split()[0])
df["score_type"] = df["index"].apply(lambda x: x.split()[1])
df["path_type"] = df["index"].apply(lambda x: x.split()[2])
df.drop("index", inplace=True, axis=1)
df = df[["sigma_min", "score_type", "path_type", "value", "time"]]
df.sort_values(["path_type", "score_type", "sigma_min"], ascending=False, inplace=True)
df

,sigma_min,score_type,path_type,value,time
9,1,tong,gaussian,"(4.47, 4.78, 5.08)","(23.35, 24.58, 25.81)"
10,0.75,tong,gaussian,"(4.46, 4.73, 5.01)","(23.02, 24.59, 26.16)"
11,0.5,tong,gaussian,"(4.73, 5.0, 5.27)","(24.09, 25.67, 27.24)"
12,0.25,tong,gaussian,"(4.85, 5.1, 5.35)","(23.7, 25.55, 27.4)"
2,1,rnl,gaussian,"(12.46, 17.05, 21.65)","(11.74, 12.84, 13.94)"
4,0.75,rnl,gaussian,"(26.8, 30.56, 34.33)","(10.67, 11.6, 12.54)"
6,0.5,rnl,gaussian,"(44.89, 64.61, 84.33)","(8.67, 9.26, 9.85)"
8,0.25,rnl,gaussian,"(169.52, 233.47, 297.41)","(6.52, 7.24, 7.96)"
1,1,-,gaussian,"(4.31, 4.64, 4.97)","(26.02, 29.46, 32.89)"
3,0.75,-,gaussian,"(4.64, 4.95, 5.26)","(25.98, 29.24, 32.51)"
5,0.5,-,gaussian,"(4.65, 5.13, 5.61)","(26.99, 30.48, 33.97)"
7,0.25,-,gaussian,"(4.59, 4.91, 5.24)","(26.17, 29.54, 32.9)"
14,0.1,rnl,dirac,"(5.26, 5.53, 5.8)","(16.44, 17.11, 17.79)"
16,0.01,rnl,dirac,"(5.58, 6.22, 6.86)","(15.58, 16.47, 17.35)"
18,0.001,rnl,dirac,"(5.77, 6.33, 6.9)","(14.8, 15.69, 16.58)"
20,0.0001,rnl,dirac,"(6.12, 6.66, 7.21)","(15.39, 15.82, 16.26)"
22,0,rnl,dirac,"(5.35, 5.78, 6.21)","(15.96, 16.61, 17.26)"
23,0.1,rl,dirac,"(4.78, 4.94, 5.11)","(29.76, 31.2, 32.64)"
24,0.01,rl,dirac,"(5.0, 5.24, 5.47)","(30.22, 31.81, 33.39)"
25,0.001,rl,dirac,"(4.86, 5.02, 5.17)","(30.6, 31.98, 33.37)"
26,0.0001,rl,dirac,"(4.86, 5.13, 5.4)","(31.06, 32.11, 33.15)"
27,0,rl,dirac,"(4.93, 5.16, 5.39)","(30.41, 31.26, 32.11)"
13,0.1,-,dirac,"(4.87, 5.01, 5.16)","(32.53, 37.13, 41.74)"
15,0.01,-,dirac,"(4.92, 5.14, 5.36)","(34.3, 39.01, 43.72)"
17,0.001,-,dirac,"(4.77, 4.95, 5.14)","(34.47, 38.84, 43.2)"
19,0.0001,-,dirac,"(4.83, 5.0, 5.18)","(34.38, 39.15, 43.92)"
21,0,-,dirac,"(4.9, 5.1, 5.3)","(34.23, 38.72, 43.21)"
0,-,-,-,"(5.01, 5.01, 5.01)","(0.0, 0.01, 0.01)"

In [13]:
# difficult example
df

,sigma_min,score_type,path_type,value,time
9,1,tong,gaussian,"(17.64, 18.19, 18.74)","(14.4, 15.15, 15.91)"
10,0.75,tong,gaussian,"(18.14, 18.77, 19.39)","(14.11, 14.79, 15.47)"
11,0.5,tong,gaussian,"(15.81, 18.08, 20.35)","(13.64, 15.64, 17.65)"
12,0.25,tong,gaussian,"(18.42, 19.23, 20.04)","(13.21, 14.38, 15.55)"
2,1,rnl,gaussian,"(70.81, 79.24, 87.67)","(6.77, 7.11, 7.46)"
4,0.75,rnl,gaussian,"(110.27, 128.32, 146.37)","(6.19, 6.3, 6.4)"
6,0.5,rnl,gaussian,"(269.79, 302.19, 334.59)","(5.75, 5.95, 6.14)"
8,0.25,rnl,gaussian,"(1098.65, 1283.85, 1469.05)","(5.55, 5.65, 5.75)"
1,1,-,gaussian,"(20.16, 21.18, 22.2)","(25.79, 29.42, 33.05)"
3,0.75,-,gaussian,"(20.1, 21.01, 21.93)","(25.63, 29.09, 32.55)"
5,0.5,-,gaussian,"(18.11, 19.87, 21.62)","(25.86, 29.8, 33.75)"
7,0.25,-,gaussian,"(20.72, 22.12, 23.53)","(25.83, 29.36, 32.88)"
14,0.1,rnl,dirac,"(35.83, 38.87, 41.91)","(8.4, 8.8, 9.19)"
16,0.01,rnl,dirac,"(50.09, 56.56, 63.02)","(7.49, 8.38, 9.27)"
18,0.001,rnl,dirac,"(66.79, 82.64, 98.49)","(7.16, 7.72, 8.27)"
20,0.0001,rnl,dirac,"(65.71, 80.04, 94.37)","(6.19, 6.63, 7.08)"
22,0,rnl,dirac,"(53.74, 62.82, 71.9)","(7.87, 8.31, 8.74)"
23,0.1,rl,dirac,"(22.93, 24.01, 25.09)","(19.46, 20.36, 21.27)"
24,0.01,rl,dirac,"(24.0, 25.29, 26.58)","(20.35, 21.69, 23.03)"
25,0.001,rl,dirac,"(23.48, 25.03, 26.58)","(20.66, 21.28, 21.91)"
26,0.0001,rl,dirac,"(23.75, 24.66, 25.57)","(19.68, 20.94, 22.21)"
27,0,rl,dirac,"(23.48, 24.57, 25.67)","(21.48, 22.75, 24.03)"
13,0.1,-,dirac,"(29.21, 31.47, 33.73)","(32.12, 36.42, 40.71)"
15,0.01,-,dirac,"(29.0, 31.32, 33.65)","(33.24, 37.88, 42.52)"
17,0.001,-,dirac,"(30.45, 33.46, 36.48)","(33.57, 38.18, 42.78)"
19,0.0001,-,dirac,"(28.12, 30.01, 31.89)","(33.96, 38.58, 43.21)"
21,0,-,dirac,"(29.16, 31.98, 34.79)","(33.8, 38.28, 42.76)"
0,-,-,-,"(20.17, 20.17, 20.17)","(0.01, 0.01, 0.01)"

In [17]:
# "easy" example
df

,sigma_min,score_type,path_type,value,time
9,1,tong,gaussian,"(17.44, 18.1, 18.77)","(20.27, 21.86, 23.45)"
10,0.75,tong,gaussian,"(17.6, 18.51, 19.43)","(21.15, 22.26, 23.36)"
11,0.5,tong,gaussian,"(17.2, 18.44, 19.68)","(21.06, 22.27, 23.47)"
12,0.25,tong,gaussian,"(16.95, 17.6, 18.26)","(21.27, 22.44, 23.61)"
2,1,rnl,gaussian,"(61.27, 72.04, 82.8)","(9.24, 10.36, 11.48)"
4,0.75,rnl,gaussian,"(110.22, 121.56, 132.89)","(9.08, 10.1, 11.12)"
6,0.5,rnl,gaussian,"(268.89, 287.44, 305.99)","(7.94, 8.46, 8.98)"
8,0.25,rnl,gaussian,"(944.22, 1066.3, 1188.39)","(6.13, 6.61, 7.1)"
1,1,-,gaussian,"(17.68, 18.76, 19.85)","(26.63, 30.08, 33.53)"
3,0.75,-,gaussian,"(17.87, 18.99, 20.11)","(25.81, 29.14, 32.47)"
5,0.5,-,gaussian,"(17.69, 20.33, 22.98)","(26.15, 30.17, 34.19)"
7,0.25,-,gaussian,"(17.55, 18.56, 19.58)","(26.38, 29.76, 33.14)"
14,0.1,rnl,dirac,"(27.95, 29.45, 30.95)","(14.35, 15.47, 16.6)"
16,0.01,rnl,dirac,"(30.02, 33.86, 37.71)","(13.55, 14.65, 15.75)"
18,0.001,rnl,dirac,"(41.83, 48.25, 54.67)","(13.76, 14.67, 15.58)"
20,0.0001,rnl,dirac,"(42.0, 54.86, 67.71)","(13.4, 14.5, 15.59)"
22,0,rnl,dirac,"(33.21, 36.31, 39.41)","(14.49, 15.03, 15.56)"
23,0.1,rl,dirac,"(19.41, 20.67, 21.93)","(25.75, 27.21, 28.66)"
24,0.01,rl,dirac,"(20.2, 20.89, 21.58)","(28.1, 29.1, 30.1)"
25,0.001,rl,dirac,"(19.94, 20.87, 21.8)","(28.07, 29.21, 30.34)"
26,0.0001,rl,dirac,"(20.64, 21.27, 21.9)","(27.35, 29.24, 31.12)"
27,0,rl,dirac,"(20.51, 21.38, 22.26)","(28.57, 29.58, 30.58)"
13,0.1,-,dirac,"(21.12, 22.16, 23.2)","(32.1, 36.51, 40.93)"
15,0.01,-,dirac,"(20.02, 20.9, 21.78)","(33.57, 37.93, 42.3)"
17,0.001,-,dirac,"(21.04, 21.88, 22.71)","(33.86, 38.57, 43.29)"
19,0.0001,-,dirac,"(20.65, 21.67, 22.69)","(33.48, 37.76, 42.05)"
21,0,-,dirac,"(20.97, 21.8, 22.63)","(33.89, 38.4, 42.91)"
0,-,-,-,"(19.95, 19.95, 19.95)","(0.01, 0.01, 0.01)"

In [21]:
# really easy example
df

,sigma_min,score_type,path_type,value,time
9,1,tong,gaussian,"(4.47, 4.78, 5.08)","(23.35, 24.58, 25.81)"
10,0.75,tong,gaussian,"(4.46, 4.73, 5.01)","(23.02, 24.59, 26.16)"
11,0.5,tong,gaussian,"(4.73, 5.0, 5.27)","(24.09, 25.67, 27.24)"
12,0.25,tong,gaussian,"(4.85, 5.1, 5.35)","(23.7, 25.55, 27.4)"
2,1,rnl,gaussian,"(12.46, 17.05, 21.65)","(11.74, 12.84, 13.94)"
4,0.75,rnl,gaussian,"(26.8, 30.56, 34.33)","(10.67, 11.6, 12.54)"
6,0.5,rnl,gaussian,"(44.89, 64.61, 84.33)","(8.67, 9.26, 9.85)"
8,0.25,rnl,gaussian,"(169.52, 233.47, 297.41)","(6.52, 7.24, 7.96)"
1,1,-,gaussian,"(4.31, 4.64, 4.97)","(26.02, 29.46, 32.89)"
3,0.75,-,gaussian,"(4.64, 4.95, 5.26)","(25.98, 29.24, 32.51)"
5,0.5,-,gaussian,"(4.65, 5.13, 5.61)","(26.99, 30.48, 33.97)"
7,0.25,-,gaussian,"(4.59, 4.91, 5.24)","(26.17, 29.54, 32.9)"
14,0.1,rnl,dirac,"(5.26, 5.53, 5.8)","(16.44, 17.11, 17.79)"
16,0.01,rnl,dirac,"(5.58, 6.22, 6.86)","(15.58, 16.47, 17.35)"
18,0.001,rnl,dirac,"(5.77, 6.33, 6.9)","(14.8, 15.69, 16.58)"
20,0.0001,rnl,dirac,"(6.12, 6.66, 7.21)","(15.39, 15.82, 16.26)"
22,0,rnl,dirac,"(5.35, 5.78, 6.21)","(15.96, 16.61, 17.26)"
23,0.1,rl,dirac,"(4.78, 4.94, 5.11)","(29.76, 31.2, 32.64)"
24,0.01,rl,dirac,"(5.0, 5.24, 5.47)","(30.22, 31.81, 33.39)"
25,0.001,rl,dirac,"(4.86, 5.02, 5.17)","(30.6, 31.98, 33.37)"
26,0.0001,rl,dirac,"(4.86, 5.13, 5.4)","(31.06, 32.11, 33.15)"
27,0,rl,dirac,"(4.93, 5.16, 5.39)","(30.41, 31.26, 32.11)"
13,0.1,-,dirac,"(4.87, 5.01, 5.16)","(32.53, 37.13, 41.74)"
15,0.01,-,dirac,"(4.92, 5.14, 5.36)","(34.3, 39.01, 43.72)"
17,0.001,-,dirac,"(4.77, 4.95, 5.14)","(34.47, 38.84, 43.2)"
19,0.0001,-,dirac,"(4.83, 5.0, 5.18)","(34.38, 39.15, 43.92)"
21,0,-,dirac,"(4.9, 5.1, 5.3)","(34.23, 38.72, 43.21)"
0,-,-,-,"(5.01, 5.01, 5.01)","(0.0, 0.01, 0.01)"